import { useCallback, useMemo, useState } from 'react';
import { ScrollView, StyleSheet, Text, View } from 'react-native';
import { useFocusEffect } from 'expo-router';
import { SignalValidationRepository } from '../db/repositories/SignalValidationRepository';
import { signalEvaluation } from '../db/schema';

type Row=typeof signalEvaluation.$inferSelect;
export default function ValidationScreen(){const[rows,setRows]=useState<Row[]>([]);const load=useCallback(async()=>{await SignalValidationRepository.evaluateMatured();setRows(await SignalValidationRepository.all())},[]);useFocusEffect(useCallback(()=>{void load()},[load]));
 const stats=useMemo(()=>{let tp=0,fp=0,tn=0,fn=0;for(const r of rows){if(!r.outcomeJson)continue;try{const c=JSON.parse(r.outcomeJson).classification;if(c==='TRUE_POSITIVE')tp++;else if(c==='FALSE_POSITIVE')fp++;else if(c==='TRUE_NEGATIVE')tn++;else if(c==='FALSE_NEGATIVE')fn++}catch{}}const precision=tp+fp?tp/(tp+fp):null,recall=tp+fn?tp/(tp+fn):null;return{tp,fp,tn,fn,precision,recall,evaluated:tp+fp+tn+fn,pending:rows.filter(x=>!x.evaluatedAt).length}},[rows]);
 return <ScrollView style={styles.screen} contentContainerStyle={styles.content}><Text style={styles.eyebrow}>ATLAS Ω · MODEL VALIDATION</Text><Text style={styles.title}>Demostrar, no asumir</Text><Text style={styles.subtitle}>Las alertas Downside se congelan al producirse y se evalúan a 7 días contra retorno y drawdown posteriores. Este panel mide utilidad observada, no promete capacidad predictiva.</Text><View style={styles.grid}><Kpi label="EVALUATED" value={String(stats.evaluated)}/><Kpi label="PENDING" value={String(stats.pending)}/><Kpi label="PRECISION" value={stats.precision==null?'—':`${(stats.precision*100).toFixed(1)}%`}/><Kpi label="RECALL" value={stats.recall==null?'—':`${(stats.recall*100).toFixed(1)}%`}/></View><View style={styles.grid}><Kpi label="TRUE +" value={String(stats.tp)} tone="good"/><Kpi label="FALSE +" value={String(stats.fp)} tone="bad"/><Kpi label="TRUE −" value={String(stats.tn)} tone="good"/><Kpi label="FALSE −" value={String(stats.fn)} tone="bad"/></View><View style={styles.guard}><Text style={styles.guardTitle}>CURRENT RULE</Text><Text style={styles.guardText}>Downside score ≥50 is a positive prediction. A material downside event is defined as drawdown ≤−5% inside the 7D evaluation window. Rules are versioned in each outcome and can be replaced after calibration.</Text></View>{rows.sort((a,b)=>b.createdAt.getTime()-a.createdAt.getTime()).map(r=><View key={r.id} style={styles.card}><View style={styles.row}><Text style={styles.signal}>{r.signalType}</Text><Text style={styles.state}>{r.state} · {r.score?.toFixed(0)??'—'}</Text></View><Text style={styles.meta}>{r.createdAt.toLocaleString('es-ES')} · horizon {r.horizon||'—'} · price {r.priceAtSignal?.toFixed(2)??'—'}</Text><Outcome json={r.outcomeJson}/></View>)}{!rows.length?<Text style={styles.empty}>Aún no hay señales registradas. Radar Ω empezará a construir el historial cuando detecte estados WATCH/ELEVATED/CRITICAL.</Text>:null}</ScrollView>}
function Outcome({json}:{json:string|null}){if(!json)return <Text style={styles.pending}>PENDING OUTCOME</Text>;try{const x=JSON.parse(json);return <Text style={styles.outcome}>{x.classification} · return {x.returnPct?.toFixed?.(2)??'—'}% · drawdown {x.drawdownPct?.toFixed?.(2)??'—'}%</Text>}catch{return <Text style={styles.pending}>INVALID OUTCOME RECORD</Text>}}
function Kpi({label,value,tone}:{label:string;value:string;tone?:'good'|'bad'}){return <View style={styles.kpi}><Text style={styles.kpiLabel}>{label}</Text><Text style={[styles.kpiValue,tone==='good'?styles.good:tone==='bad'?styles.bad:null]}>{value}</Text></View>}
const styles=StyleSheet.create({screen:{flex:1,backgroundColor:'#05080c'},content:{padding:14,paddingBottom:42,gap:10},eyebrow:{color:'#617589',fontSize:9,fontWeight:'900',letterSpacing:1.4},title:{color:'#eff4f8',fontSize:24,fontWeight:'900'},subtitle:{color:'#728497',fontSize:11,lineHeight:17},grid:{flexDirection:'row',gap:5},kpi:{flex:1,backgroundColor:'#090e14',borderWidth:1,borderColor:'#17222e',borderRadius:8,padding:9},kpiLabel:{color:'#526476',fontSize:6,fontWeight:'900'},kpiValue:{color:'#c2ced8',fontSize:16,fontWeight:'900',marginTop:4},good:{color:'#4fdca3'},bad:{color:'#ff697c'},guard:{backgroundColor:'#161309',borderWidth:1,borderColor:'#4e4219',borderRadius:8,padding:10},guardTitle:{color:'#d8b958',fontSize:8,fontWeight:'900'},guardText:{color:'#92804c',fontSize:9,lineHeight:14,marginTop:3},card:{backgroundColor:'#090e14',borderWidth:1,borderColor:'#17222e',borderRadius:8,padding:10,gap:4},row:{flexDirection:'row',justifyContent:'space-between'},signal:{color:'#dce6ed',fontSize:10,fontWeight:'900'},state:{color:'#94a8b9',fontSize:8,fontWeight:'900'},meta:{color:'#586b7d',fontSize:7},pending:{color:'#d4b556',fontSize:8,fontWeight:'900',marginTop:3},outcome:{color:'#8db6c8',fontSize:8,fontWeight:'800',marginTop:3},empty:{color:'#617386',textAlign:'center',marginTop:30,lineHeight:17}});
