import http from 'node:http';
import { marketSignals } from './market-engine.mjs';
import { runFundamentalAudit } from './fundamental-engine.mjs';

const PORT=Number(process.env.PORT||8787), HOST=process.env.HOST||'0.0.0.0';
const rows=Array.from({length:260},(_,i)=>({t:new Date(Date.UTC(2025,0,1+i)).toISOString(),o:100+i*.55,h:101+i*.55,l:99+i*.55,c:100+i*.55,v:i>=255?1600000:1000000}));
const signals=marketSignals(rows);
const metric={roeTTM:32,roaTTM:14,operatingMarginTTM:31,netProfitMarginTTM:24,grossMarginTTM:68,revenueGrowth3Y:18,revenueGrowthTTMYoy:20,epsGrowth3Y:22,epsGrowthTTMYoy:25,currentRatioAnnual:1.8,quickRatioAnnual:1.4,totalDebtToEquityAnnual:55,freeCashFlowPerShareTTM:8.2,freeCashFlowYieldTTM:4.5,peTTM:28,pbAnnual:8,evEbitdaTTM:20,beta:1.05,marketCapitalization:300000};
const filing={form:'10-Q',filingDate:'2026-07-30',reportDate:'2026-06-30',accessionNumber:'0000000000-26-000001',primaryDocument:'fixture10q.htm',items:[],eventClass:'PERIODIC_REPORT',materialityScore:70,validationState:'PENDING_PRIMARY_VALIDATION',requiresHumanReview:true};
const audit=runFundamentalAudit({metric,marketSignals:signals,marketCap:300000,evidence:[filing]});
const quote={provider:'FIXTURE',ticker:'NVDA',price:243.1,change:3.1,changePct:1.29,open:240,high:245,low:239,previousClose:240,timestamp:new Date().toISOString(),session:'REGULAR'};
const security={canonicalTicker:'NVDA',companyName:'NVIDIA Corporation · CI FIXTURE',exchange:'NASDAQ',country:'US',sector:'Semiconductors',industry:'Semiconductors',currency:'USD',marketCap:300000,provider:'FIXTURE',resolvedAt:new Date().toISOString()};
const bundle=()=>({security,quote,history:rows,marketSignals:signals,fundamentals:{provider:'FIXTURE',ticker:'NVDA',metric,series:{},observedAt:new Date().toISOString()},news:[{id:'fixture-news',headline:'Deterministic fixture event',summary:'CI fixture only',source:'ATLAS CI',url:'',datetime:new Date().toISOString()}],edgar:{ticker:'NVDA',cik:'0000000000',status:'OK',filings:[filing],observedAt:new Date().toISOString()},canonicalAudit:audit,generatedAt:new Date().toISOString()});
const send=(res,status,body)=>{res.writeHead(status,{'content-type':'application/json','access-control-allow-origin':'*'});res.end(JSON.stringify(body))};
const server=http.createServer((req,res)=>{const u=new URL(req.url||'/',`http://${req.headers.host||'localhost'}`);if(u.pathname==='/health')return send(res,200,{ok:true,service:'ATLAS Ω CI Fixture',version:'fixture-1',providers:{finnhub:'FIXTURE',secEdgar:'CONFIGURED',trading212:'CONFIGURED_READ_ONLY'},engines:{market:signals.algorithmVersion,fundamental:audit.algorithmVersion},invariants:{marketDataIsSensor:true,aiIsNeverEvidence:true,priceCannotMutateThesisDirectly:true,brokerWriteEndpoints:false},time:new Date().toISOString()});if(u.pathname==='/v1/portfolio')return send(res,200,{provider:'TRADING212-FIXTURE',environment:'ci',readOnlyGuard:true,account:{currency:'EUR'},positions:[{brokerTicker:'NVDA_US_EQ',ticker:'NVDA',name:'NVIDIA Corporation · CI FIXTURE',isin:'US67066G1040',currency:'USD',quantity:2,averagePrice:200,currentPrice:243.1,walletImpact:null,createdAt:'2026-01-01T00:00:00Z'}],observedAt:new Date().toISOString()});if(u.pathname==='/v1/discovery')return send(res,200,{generatedAt:new Date().toISOString(),methodology:'CI deterministic ticker-first fixture',items:[{ticker:'NVDA',price:243.1,dayPct:1.29,discoveryScore:88,...signals}]});if(u.pathname.startsWith('/v1/search'))return send(res,200,security);if(u.pathname.startsWith('/v1/quote/'))return send(res,200,quote);if(u.pathname.startsWith('/v1/history/'))return send(res,200,{ticker:'NVDA',range:u.searchParams.get('range')||'1Y',rows});if(u.pathname.startsWith('/v1/signals/'))return send(res,200,{ticker:'NVDA',...signals});if(u.pathname.startsWith('/v1/terminal/')||u.pathname.startsWith('/v1/audit/'))return send(res,200,bundle());if(u.pathname.startsWith('/v1/edgar/'))return send(res,200,bundle().edgar);return send(res,404,{error:'NOT_FOUND'})});
server.listen(PORT,HOST,()=>console.log(`ATLAS CI fixture server on ${HOST}:${PORT}`));
