export const ATLAS_PRIMARY_ENGINE_HIERARCHY = {
  version: '2026-08-20-v4.5.2',
  primaryEngine: 'PRINCIPAL_OMEGA',
  primaryRole: 'structural_selection_quality_growth_asymmetry',
  refinementEngines: [
    'LEADERSHIP_BIAS_CONTROL_OMEGA_V1', 'SUCCESSOR_DETECTION_OMEGA_V1_1', 'GREEN_CONTINUITY_OMEGA_V1_1',
    'BUSINESS_QUALITY_OMEGA', 'GROWTH_OMEGA', 'CAPEX_PRODUCTIVITY_OMEGA', 'ECONOMIC_THROUGHPUT_GATE_OMEGA_V1',
    'VALUATION_OMEGA', 'RISK_OMEGA', 'GLOBAL_LIQUIDITY_TRANSMISSION_OMEGA_V2', 'SPECULATIVE_LIQUIDITY_CANARY_OMEGA_V1',
    'SOVEREIGN_LIQUIDITY_PLUMBING_OMEGA_V1', 'SOVEREIGN_GOLD_ACCUMULATION_OMEGA_V1',
    'INSTITUTIONAL_CAPITAL_ROTATION_OMEGA_V1_1', 'INSTITUTIONAL_CONVERGENCE_OMEGA_V1', 'MONEY_ROTATION_OMEGA',
    'ENERGY_ROTATION_OMEGA', 'EUROPEAN_FRAGMENTATION_ENERGY_SECURITY_OMEGA_V1_1', 'EU_FISCAL_STRESS_OMEGA_V1',
    'CHINA_INDUSTRIAL_DISPLACEMENT_OMEGA_V1', 'GOOD_COMPANIES_CHEAP_OMEGA', 'HISTORICAL_DISLOCATION_OMEGA',
    'SPECIALIZED_ENGINES_OMEGA', 'SIZE_NEUTRAL_RETURN_RANKING_OMEGA_V1',
  ] as const,
  conditionalSpecializedEngines: [
    'AI_DEMAND_MONETIZATION_PROOF_OMEGA_V1',
    'NEOCLOUD_CUSTOMER_ACCEPTANCE_GATE_OMEGA_V1',
    'AI_CAPEX_PAYBACK_OMEGA_V2_1', 'AI_ECONOMIC_PROOF_EQUITY_MONETIZATION_OMEGA_V1',
    'AI_FINANCIAL_FRAGILITY_OMEGA_V1_1', 'AI_CREDIT_TRANSMISSION_OMEGA_V1',
    'GRID_BOTTLENECK_POWER_CAPTURE_OMEGA_V1',
    'MARKET_TOP_RISK_OMEGA', 'MARKET_BOTTOM_DETECTION_OMEGA', 'ENTRY_TIMING_RETURN_AWARE_OMEGA_V2_1',
    'EVENT_PRICING_OPTIONS_EXPECTATIONS_OMEGA_V1', 'SPECIAL_SITUATIONS_OMEGA_V1',
  ] as const,
  auxiliaryLayers: ['WINNER_PRESERVATION_OMEGA_V1', 'OPTIONALITY_RESERVE_OMEGA_V1', 'CAPITAL_SAFETY_LEVERAGE_DISCIPLINE_OMEGA_V1'] as const,
  transversalGates: [
    'ANTI_DELUSION_CORE_OMEGA', 'EVIDENCE_INTEGRITY_OMEGA', 'SOURCE_AUTHENTICITY_OMEGA', 'QUANTITATIVE_INTEGRITY_OMEGA',
    'TEMPORAL_NORMALIZATION_OMEGA', 'SIZE_NEUTRALITY_AUDIT_OMEGA_V1', 'SYSTEMIC_CASCADE_OMEGA_V1',
    'FALSIFIER_VETO_OMEGA_V1', 'DECISION_SAFETY_GATE_OMEGA',
  ] as const,
  rules: [
    'PRINCIPAL OMEGA remains the structural selection engine.',
    'ECONOMIC THROUGHPUT GATE measures Demand -> Capture -> Conversion -> FCF -> ROIC; activity is not economic proof.',
    'FALSIFIER VETO is independent and absolute: a confirmed structural falsifier overrides E-Proof, valuation and Expected Return.',
    'Unverified evidence cannot be promoted to a confirmed falsifier.',
    'Price is not evidence and a trigger is not a falsifier.',
    'SIZE-NEUTRAL RETURN RANKING starts every ticker at 0/1000; market cap and generic quality provide zero bonus and zero penalty.',
    'Market-cap bucket is assigned only after score freeze; size distribution is an audit output, never a score input.',
    'Growth Saturation may reduce expected-return opportunity only from economic evidence, never from size alone.',
    'ENTRY TIMING RETURN-AWARE credits the correction already observed before calculating any remaining pullback requirement.',
    'Current drawdown from ATH or rolling peak is preferred to a negative window return; window return is a fallback only when peak data are unavailable.',
    'No universal extra -3%, -5% or -10% correction may be demanded after ticker-specific dislocation bands are already reached.',
    'GREEN 5/5 remains strongest continuity; GREEN 4/5 and 3/5 are valid committee inputs when Size-Neutral Return Score is >=850. GREEN remains independent and is never rewritten by return score.',
    'GREEN below 3/5 blocks immediate entry but is not by itself a fundamental falsifier.',
    'AI DEMAND MONETIZATION PROOF must normalize run-rate versus realized TTM revenue and distinguish usage from paying/economically valuable demand.',
    'AI DEMAND MONETIZATION PROOF feeds demand/utilization evidence into AI CAPEX PAYBACK without double-counting.',
    'NEOCLOUD CUSTOMER ACCEPTANCE GATE is mandatory between Deployment and Revenue Recognition for material neocloud deployments; contract or deployment alone remains capped at E2.',
    'Customer acceptance strengthens execution proof but E3 still requires attributable recognized revenue plus credible margin.',
    'AI CAPEX PAYBACK must audit price-volume-cost elasticity: unit price declines are not payback failure unless volume, unit-cost and indirect monetization fail to offset them.',
    'AI ECONOMIC PROOF and AI EQUITY MONETIZATION are orthogonal: the business can capture AI value while the stock market refuses to reward it.',
    'AI EQUITY MONETIZATION forbids less-damaged or strong-RS stocks from being called CONFIRMED RECEIVER unless verified price continuity, flow, price response and proximity to Tmax also pass.',
    'PROOF_UP_MONETIZATION_DOWN is WATCH_FOR_REMONETIZATION by default and is never an automatic BUY.',
    'AI FINANCIAL FRAGILITY must separate recognized debt, recognized leases, non-commenced leases, purchase commitments and contingent/backstop exposure.',
    'AI FINANCIAL FRAGILITY and AI CREDIT TRANSMISSION remain independent from AI CAPEX PAYBACK and cannot double-count evidence.',
    'GRID BOTTLENECK POWER CAPTURE must normalize interconnection queues by stage; queued MW is never treated as firm load by itself.',
    'GRID BOTTLENECK POWER CAPTURE feeds Global CAPEX Chain and Power Owners but requires backlog/margin/FCF proof before economic capture is confirmed.',
    'W2_YELLOW_HIGH is a surveillance overlay, not a structural F3/F4 state and not a confirmed falsifier.',
    'SYSTEMIC CASCADE escalates only on temporally aligned multi-channel evidence and never emits a structural SELL by itself.',
    'WINNER PRESERVATION prevents automatic profit-taking solely because a validated leader has multiplied.',
  ] as const,
} as const;

export const ATLAS_CANONICAL_DECISION_SEQUENCE = [
  'INPUT',
  'ANTI_DELUSION_CORE_OMEGA',
  'EVIDENCE_INTEGRITY_OMEGA',
  'SOURCE_AUTHENTICITY_OMEGA',
  'QUANTITATIVE_INTEGRITY_OMEGA',
  'TEMPORAL_NORMALIZATION_OMEGA',
  'GLOBAL_DISCOVERY_OMEGA',
  'LEADERSHIP_BIAS_CONTROL_OMEGA_V1',
  'PRINCIPAL_OMEGA',
  'SUCCESSOR_DETECTION_OMEGA_V1_1',
  'GREEN_CONTINUITY_OMEGA_V1_1',
  'BUSINESS_QUALITY_OMEGA',
  'GROWTH_OMEGA',
  'CAPEX_PRODUCTIVITY_OMEGA',
  'ECONOMIC_THROUGHPUT_GATE_OMEGA_V1',
  'VALUATION_OMEGA',
  'EXPECTED_RETURN_3_6Y',
  'RISK_OMEGA',
  'GLOBAL_LIQUIDITY_TRANSMISSION_OMEGA_V2',
  'SPECULATIVE_LIQUIDITY_CANARY_OMEGA_V1',
  'SOVEREIGN_LIQUIDITY_PLUMBING_OMEGA_V1',
  'SOVEREIGN_GOLD_ACCUMULATION_OMEGA_V1',
  'INSTITUTIONAL_CAPITAL_ROTATION_OMEGA_V1_1',
  'INSTITUTIONAL_CONVERGENCE_OMEGA_V1',
  'MONEY_ROTATION_OMEGA',
  'ENERGY_ROTATION_OMEGA_WHEN_APPLICABLE',
  'EUROPEAN_FRAGMENTATION_ENERGY_SECURITY_OMEGA_WHEN_APPLICABLE',
  'EU_FISCAL_STRESS_OMEGA_WHEN_APPLICABLE',
  'CHINA_INDUSTRIAL_DISPLACEMENT_OMEGA_WHEN_APPLICABLE',
  'GOOD_COMPANIES_CHEAP_OMEGA_WHEN_APPLICABLE',
  'HISTORICAL_DISLOCATION_OMEGA_WHEN_APPLICABLE',
  'AI_DEMAND_MONETIZATION_PROOF_OMEGA_V1_WHEN_APPLICABLE',
  'NEOCLOUD_CUSTOMER_ACCEPTANCE_GATE_OMEGA_V1_WHEN_APPLICABLE',
  'AI_CAPEX_PAYBACK_OMEGA_V2_1_WHEN_APPLICABLE',
  'AI_ECONOMIC_PROOF_EQUITY_MONETIZATION_OMEGA_V1_WHEN_APPLICABLE',
  'AI_FINANCIAL_FRAGILITY_OMEGA_V1_1_WHEN_APPLICABLE',
  'AI_CREDIT_TRANSMISSION_OMEGA_V1_WHEN_APPLICABLE',
  'GRID_BOTTLENECK_POWER_CAPTURE_OMEGA_V1_WHEN_APPLICABLE',
  'SPECIALIZED_ENGINES_OMEGA_WHEN_APPLICABLE',
  'SYSTEMIC_CASCADE_OMEGA_V1',
  'WINNER_PRESERVATION_OMEGA_V1',
  'OPTIONALITY_RESERVE_OMEGA_V1',
  'SIZE_NEUTRAL_RETURN_RANKING_OMEGA_V1',
  'ENTRY_TIMING_RETURN_AWARE_OMEGA_V2_1',
  'SIZE_NEUTRALITY_AUDIT_OMEGA_V1',
  'FALSIFIER_VETO_OMEGA_V1',
  'DECISION_SAFETY_GATE_OMEGA',
  'DECISION_LOG_OMEGA',
  'GITHUB_NOTION_PERSISTENCE',
] as const;
