export const ATLAS_KERNEL_CONTRACT_REGISTRY_OMEGA_VERSION = '2026-09-06-v3.0.0' as const;

export const ATLAS_KERNEL_CONTRACT_REGISTRY_OMEGA = {
  governanceStatus: 'ACTIVE_CANONICAL',
  masterSelectionAuthority: {
    id: 'ATLAS_OMEGA_MASTER_UNIVERSE_PROMPT_2026_09_06',
    path: 'docs/canon/ATLAS_OMEGA_MASTER_PROMPT_CANONICAL.md',
    universeVersion: 'ATLAS_CORE_650_RAW_490_UNIQUE_487_ENTITY_2026-09-06',
    authority: 'SOLE_CLEAN_REBUILD_RANKING_MEMBERSHIP_REPLACEMENT_AND_OPTIMAL_N_AUTHORITY',
    pointZero: true,
    fixedCardinalityBoundsPermitted: false,
    priorPromptAuthority: 'SUPERSEDED',
    priorPortfolioThesisAuthority: 'SUPERSEDED',
    priorTopNAuthority: 'SUPERSEDED',
  },
  contracts: {
    delta: { id: 'DELTA_DIVERGENCE_OMEGA_V1_1', runtimeAuthority: 'SHADOW_ONLY' },
    kappa: { id: 'KAPPA_CALIBRATION_OMEGA_V1_1', runtimeAuthority: 'CALIBRATION_ONLY' },
    gamma: { id: 'GAMMA_VIGENCIA_OMEGA_V1_2', runtimeAuthority: 'VIGENCIA_ONLY' },
    upsilon: { id: 'UPSILON_ALLOCATION_OMEGA_V1', runtimeAuthority: 'ALLOCATION_ONLY' },
    rho: { id: 'RHO_COUNTERPARTY_EXPOSURE_OMEGA_V1', runtimeAuthority: 'EXPOSURE_AGGREGATION_ONLY' },
    durableRevisionGap: {
      id: 'DURABLE_REVISION_GAP_OMEGA_V1',
      runtimeAuthority: 'SUBORDINATE_SELECTION_INPUT',
      scoreAuthority: 'ECONOMIC_EVIDENCE_COMPONENT_ONLY',
    },
    revealedCapitalIntelligence: {
      id: 'REVEALED_CAPITAL_INTELLIGENCE_OMEGA_V1',
      runtimeAuthority: 'AUTHORIZED_DISCOVERY_AND_CORROBORATIVE_EVIDENCE_ONLY',
      directScoreWeight: 0,
    },
    traderIntelligence: {
      id: 'TRADER_INTELLIGENCE_OMEGA_V1',
      runtimeAuthority: 'AUTHORIZED_DISCOVERY_RESEARCH_PRIORITY_AND_FALSIFICATION_ONLY',
      directScoreWeight: 0,
      portfolioOrderAuthority: false,
    },
    capitalBlindSelection: {
      id: 'CAPITAL_BLIND_PORTFOLIO_SELECTION_OMEGA_V2',
      runtimeAuthority: 'MASTER_SUBORDINATE_PORTFOLIO_UTILITY_ENGINE',
      fixedCardinalityBoundsPermitted: false,
    },
    endogenousPortfolio: {
      id: 'ENDOGENOUS_PORTFOLIO_ENGINE_V2_2',
      runtimeAuthority: 'MASTER_SUBORDINATE_PORTFOLIO_UTILITY_ENGINE',
      fixedCardinalityBoundsPermitted: false,
      replacementHysteresisAuthority: 'EXECUTION_ONLY',
    },
  },
  boundaries: {
    everyCanonicalEntityStartsWithZeroPriorAdvantage: true,
    duplicateRawRowsCannotCreateExtraSelectionOpportunities: true,
    fixedNTargetsForbidden: true,
    incumbentProtectionForbiddenDuringCleanRebuild: true,
    marketCapBonusForbidden: true,
    fameFamiliarityBonusForbidden: true,
    indexMembershipBonusForbidden: true,
    currentPortfolioStateCannotAffectMembership: true,
    externalChallengerStatusCreatesZeroScore: true,
    aestheticDiversificationQuotaForbidden: true,
    realCorrelatedRiskMustBeModeled: true,
    tapeRsCannotReplaceFundamentals: true,
    unknownDataMustReduceConfidence: true,
    deltaCannotConclude: true,
    deltaCannotModulateCoreConfidenceWhileShadow: true,
    kappaCannotChangeMethodology: true,
    gammaCannotBuySell: true,
    upsilonCannotAdmitExclude: true,
    rhoCannotBuySell: true,
    rhoCannotSetWeight: true,
    rhoCannotAdmitExclude: true,
    revealedCapitalCannotCreateDirectScore: true,
    revealedCapitalCannotBypassFundamentals: true,
    revealedCapitalCannotBypassValuation: true,
    revealedCapitalCannotBypassFalsifierVeto: true,
    traderIdentityCannotCreateDirectScore: true,
    traderIntelligenceCannotBuySell: true,
    traderIntelligenceCannotSetWeight: true,
    traderIntelligenceCannotBypassFundamentals: true,
    traderIntelligenceCannotBypassValuation: true,
    traderIntelligenceCannotBypassCompetitionForCapital: true,
    traderIntelligenceCannotBypassFalsifierVeto: true,
    traderDerivedRulesRequireAuthorRemovalTest: true,
    durableRevisionGapRequiresIndependentFundamentalEvidence: true,
    falsifierVetoIndependent: true,
    decisionSafetyIndependent: true,
  },
  mainSelectionSequence: [
    'CANONICAL_ENTITY_NORMALIZATION_AND_DEDUP_650_RAW_490_TICKERS_487_ENTITIES',
    'POINT_ZERO_ZERO_PRIOR_ADVANTAGE',
    'T0_ANTI_MEGACAP_DISCOVERY_GATE_OMEGA',
    'BROAD_UNIVERSE_SCREENING',
    'PRINCIPAL_OMEGA',
    'BUSINESS_QUALITY_OMEGA',
    'GROWTH_AND_REVISIONS_OMEGA',
    'PER_SHARE_ECONOMICS_OMEGA_V1',
    'OWNER_ECONOMICS_NORMALIZATION_OMEGA_V1',
    'DURABLE_REVISION_GAP_OMEGA_V1',
    'VALUATION_OMEGA',
    'EXPECTED_RETURN_3_6Y',
    'FCF_MARGINS_ROIC_BALANCE_SHEET',
    'MOAT_AND_DISRUPTION_RISK',
    'AI_VALUE_MIGRATION_WHEN_APPLICABLE',
    'AI_CAPITAL_FORMATION_WHEN_APPLICABLE',
    'EXPECTATION_GAP_OMEGA',
    'TAPE_RS_COMPLEMENTARY_ONLY',
    'MACRO_REGULATORY_GEOPOLITICAL_FINANCING_RISK',
    'FALSIFIERS_OMEGA',
    'ECONOMIC_COMPARABLE_DUELS',
    'CROSS_SECTOR_COMPETITION_FOR_CAPITAL_OMEGA',
    'CAPITAL_BLIND_WHOLE_PORTFOLIO_UTILITY_SELECTION',
    'FULLY_ENDOGENOUS_OPTIMAL_N',
    'HIDDEN_FACTOR_CONCENTRATION_AUDIT',
    'BULL_BASE_BEAR_SENSITIVITY',
    'ANTI_BIAS_AUDIT',
  ],
  aiCapexPreScoreSequence: [
    'T0_ANTI_MEGACAP_DISCOVERY_GATE_OMEGA',
    'T1_FUNDAMENTAL_HARD_GATES',
    'T2_FINANCING_QUALITY_GATE_OMEGA_V1',
    'T3_CIRCULAR_DEMAND_GATE_OMEGA_V1',
    'T4_QUALITY_ADJUSTED_BACKLOG_OMEGA_V1',
    'T5_CAPITAL_RISK_TRANSFER_ADVANTAGE_OMEGA_V1',
    'ATLAS_FUNDAMENTAL_SCORE',
  ],
  finalRule: 'NO_INTENTES_JUSTIFICAR_LA_CARTERA_QUE_YA_TENEMOS_INTENTA_DERROTARLA',
} as const;