export const ATLAS_KERNEL_CONTRACT_REGISTRY_OMEGA_VERSION = '2026-09-07-v4.2.0' as const;

export const ATLAS_KERNEL_CONTRACT_REGISTRY_OMEGA = {
  governanceStatus: 'ACTIVE_CANONICAL',
  architectureConsolidation: {
    authority: 'CURRENT_CANON/2026-09-07_ASTRA_CONSOLIDATION_RATIFICATION_v1_0.md',
    pointZeroAppliedToAtlasItself: true,
    canonicalEngineCount: 6,
    noNewCanonicalEngineWithoutUniqueMeasuredCapability: true,
    provenanceDeletionAuthorized: false,
    frozenStateExclusivePerLogicalObject: true,
  },
  canonicalArchitecture: {
    R0: { id: 'RESEARCH_OMEGA', kind: 'RESEARCH_SUBSTRATE', rankingAuthority: false, canonWriteAuthority: false },
    E1: { id: 'EVIDENCE_OMEGA', kind: 'CANONICAL_ENGINE', question: 'WHAT_IS_KNOWN_WITH_WHAT_PROVENANCE_AT_WHAT_TIME' },
    E2: { id: 'ASSESSMENT_OMEGA', kind: 'CANONICAL_ENGINE', question: 'WHAT_DO_VALID_ALIGNED_INPUTS_SUPPORT' },
    E3: { id: 'GATE_OMEGA', kind: 'CANONICAL_ENGINE', question: 'IS_THERE_A_BINDING_REASON_NOT_TO_PROCEED', outputType: 'BOOLEAN_OR_CONDITIONAL' },
    E4: { id: 'DECISION_OMEGA', kind: 'CANONICAL_ENGINE', question: 'WHAT_SHOULD_BE_DONE_WITH_CAPITAL_OR_ACTION_STATE' },
    E5: { id: 'CONTROL_OMEGA', kind: 'CANONICAL_ENGINE', question: 'WHO_MAY_DO_WHAT_UNDER_WHICH_REVOCABLE_CONDITIONS' },
    E6: { id: 'ASSURANCE_OMEGA', kind: 'CANONICAL_ENGINE', question: 'DOES_ATLAS_DO_WHAT_IT_CLAIMS_AGAINST_INDEPENDENT_TRUTH' },
  },
  hardPlaneSeparation: [
    'RESEARCH',
    'SIGNAL',
    'SCORE',
    'GATE',
    'PORTFOLIO_SELECTION',
    'EXECUTION',
  ],
  researchPrograms: {
    P1: 'DONDE_VA_EL_CAPITAL',
    P2: 'QUIEN_CAPTURA_EL_VALOR',
    P3: 'COMO_SE_TRANSMITE_EL_REGIMEN',
    economicArchaeology: 'E6_VALIDATION_METHOD_NOT_DECISION_ENGINE',
    realWorldIntelligence: 'LIQUID_P2_RESEARCH_UNTIL_MEASURABLE_CAPABILITY_EXISTS',
  },
  ratifiedDecisions: {
    currentOperationalPortfolioObject: 'CURRENT_CANON/2026-09-06_ATLAS_CURRENT_OPERATIONAL_PORTFOLIO_27.md',
    officialInvestmentHorizon: '3-6_YEARS',
    strategicCriticality: 'SEPARATE_REPORTED_AXIS_NOT_SUMMED_INTO_POINT_ZERO_QUALITY',
    breadthRotationWeight: 0,
    breadthRotationAuthority: 'SHADOW_SIGNAL_DISCOVERY_ONLY',
    learningOmegaAuthority: 'HYPOTHESIS_GENERATOR_ONLY',
    frozenAuthorityRule: 'EXACTLY_ONE_CURRENT_FROZEN_AUTHORITY_PER_LOGICAL_OBJECT',
    aiExposureControl: {
      authority: 'CURRENT_CANON/2026-09-07_ATLAS_AI_EXPOSURE_CONTROL_OMEGA.md',
      aiCoreBaseCeiling: 0.30,
      ceilingType: 'DEFAULT_OPERATIONAL_CEILING_NOT_SELECTION_QUOTA',
      conditionalOverride: 'AI_MOMENTUM_OVERRIDE',
      momentumAloneSufficient: false,
      passiveDriftAboveCeilingAutoSell: false,
      deliberateIncreaseAboveCeilingRequiresHumanApproval: true,
      legacyFixedAiCapsSuperseded: true,
    },
  },
  permissionModel: {
    permissions: ['READ','WRITE','EXECUTE','COMMUNICATE','PERSIST','SCHEDULE','DELEGATE','MODIFY_CANON'],
    noPermissionIsImpliedByAnother: true,
    automaticModifyCanonAllowed: false,
    humanAuthority: 'FULL_AND_FINAL',
    predictiveAccuracyCannotExpandPermissions: true,
  },
  masterSelectionAuthority: {
    id: 'ATLAS_OMEGA_MASTER_UNIVERSE_PROMPT_2026_09_07',
    path: 'docs/canon/ATLAS_OMEGA_MASTER_PROMPT_CANONICAL.md',
    universeVersion: 'ATLAS_CORE_650_RAW_490_UNIQUE_487_ENTITY_2026-09-06',
    authority: 'SOLE_CLEAN_REBUILD_RANKING_MEMBERSHIP_REPLACEMENT_AND_OPTIMAL_N_AUTHORITY',
    pointZero: true,
    fixedCardinalityBoundsPermitted: false,
    priorPromptAuthority: 'SUPERSEDED',
    priorPortfolioThesisAuthority: 'SUPERSEDED',
    priorTopNAuthority: 'SUPERSEDED',
  },
  contracts: {
    economicImplementation: {
      authority: 'CURRENT_CANON/2026-09-07_ECONOMIC_CONTRACT_IMPLEMENTATION.md',
      scenarioReturn: {host:'E2', implementation:'scenario-owner-return-omega.ts', status:'IMPLEMENTED_CONDITIONAL_ASSESSMENT'},
      netRotation: {host:'E3', implementation:'net-rotation-advantage-omega.ts', executionAuthority:false},
      aiControl: {host:'E5', implementation:'e5-control-policy-omega.ts', orderAuthority:false},
      measuredCovariance: {host:'E2', implementation:'structural-risk-unit-authority-omega.ts'},
      sizing: {host:'E4', implementation:'structural-sizing-authority-omega.ts', status:'SHADOW_ONLY'},
      exactSmallUniverseReference: {host:'E6', implementation:'e6-assurance-harness-policy-omega.ts', status:'EVALUATION_ONLY'},
      economicCalibrationPromoted:false,
    },
    delta: { id: 'DELTA_DIVERGENCE_OMEGA_V1_1', runtimeAuthority: 'SHADOW_ONLY' },
    kappa: { id: 'KAPPA_CALIBRATION_OMEGA_V1_1', runtimeAuthority: 'CALIBRATION_ONLY' },
    gamma: { id: 'GAMMA_VIGENCIA_OMEGA_V1_2', runtimeAuthority: 'VIGENCIA_ONLY' },
    upsilon: { id: 'UPSILON_ALLOCATION_OMEGA_V1', runtimeAuthority: 'ALLOCATION_ONLY' },
    rho: { id: 'RHO_COUNTERPARTY_EXPOSURE_OMEGA_V1', runtimeAuthority: 'EXPOSURE_AGGREGATION_ONLY' },
    aiExposureControl: {
      id: 'AI_EXPOSURE_CONTROL_OMEGA_2026_09_07',
      runtimeAuthority: 'PORTFOLIO_SIZING_AND_CORRELATED_RISK_CONTROL_ONLY',
      aiCoreBaseCeiling: 0.30,
      overrideStatus: 'AI_MOMENTUM_OVERRIDE',
      pointZeroRankingPenaltyAuthority: false,
      nonAiDiversificationBonusAuthority: false,
      momentumAloneSufficient: false,
      requiredOverrideEvidence: [
        'PERSISTENT_TAPE_RS_MOMENTUM',
        'FUNDAMENTALS_HEALTHY',
        'REVISIONS_AND_ECONOMIC_PROOF_SUPPORTIVE',
        'VALUATION_AND_EXPECTED_RETURN_PASS',
        'EXPECTATION_GAP_ACCEPTABLE',
        'CORRELATED_RISK_STRESS_ACCEPTABLE',
        'HUMAN_APPROVAL_FOR_DELIBERATE_OVER_30_INCREASE',
      ],
    },
    durableRevisionGap: {
      id: 'DURABLE_REVISION_GAP_OMEGA_V1',
      runtimeAuthority: 'SUBORDINATE_SELECTION_INPUT',
      scoreAuthority: 'ECONOMIC_EVIDENCE_COMPONENT_ONLY',
    },
    ownerEconomicsRotationSpecialized: {
      id: 'OWNER_ECONOMICS_ROTATION_SPECIALIZED_OMEGA',
      runtimeAuthority: 'SUBORDINATE_EVIDENCE_NORMALIZATION_AND_RISK_INPUTS_ONLY',
      incumbentPreferenceAuthority: false,
    },
    investmentDisciplineCompounding: {
      id: 'INVESTMENT_DISCIPLINE_COMPOUNDING_OMEGA_V1',
      runtimeAuthority: 'SUBORDINATE_FUNDAMENTAL_DIAGNOSTICS_ONLY',
      antiChurnReplacementHurdleAuthority: 'EXECUTION_ONLY_LEGACY_COMPATIBILITY',
      activeVsIndexAuthority: 'DIAGNOSTIC_ONLY',
      incumbentPreferenceAuthority: false,
    },
    leadershipBiasControl: {
      id: 'LEADERSHIP_BIAS_CONTROL_OMEGA',
      runtimeAuthority: 'DISCOVERY_AND_COMPARISON_ONLY',
      incumbentLabelAuthority: false,
      portfolioMembershipAuthority: false,
    },
    propicksChallengerReplacementAlpha: {
      id: 'PROPICKS_CHALLENGER_REPLACEMENT_ALPHA_OMEGA',
      runtimeAuthority: 'RESEARCH_AND_EXECUTION_TEST_ONLY',
      cleanSelectionAuthority: false,
    },
    revealedCapitalIntelligence: {
      id: 'REVEALED_CAPITAL_INTELLIGENCE_OMEGA_V1',
      runtimeAuthority: 'AUTHORIZED_DISCOVERY_AND_CORROBORATIVE_EVIDENCE_ONLY',
      directScoreWeight: 0,
    },
    traderIntelligence: {
      id: 'TRADER_INTELLIGENCE_OMEGA_V1',
      runtimeAuthority: 'AUTHORIZED_DISCOVERY_RESEARCH_PRIORITY_AND_FALSIFICATION_ONLY',
      directScoreWeight: 0,
      portfolioOrderAuthority: false,
    },
    capitalBlindSelection: {
      id: 'CAPITAL_BLIND_PORTFOLIO_SELECTION_OMEGA_V2',
      runtimeAuthority: 'MASTER_SUBORDINATE_PORTFOLIO_UTILITY_ENGINE',
      fixedCardinalityBoundsPermitted: false,
    },
    endogenousPortfolio: {
      id: 'ENDOGENOUS_PORTFOLIO_ENGINE_V2_2',
      runtimeAuthority: 'MASTER_SUBORDINATE_PORTFOLIO_UTILITY_ENGINE',
      fixedCardinalityBoundsPermitted: false,
      replacementHysteresisAuthority: 'EXECUTION_ONLY',
    },
  },
  boundaries: {
    everyCanonicalEntityStartsWithZeroPriorAdvantage: true,
    duplicateRawRowsCannotCreateExtraSelectionOpportunities: true,
    fixedNTargetsForbidden: true,
    incumbentProtectionForbiddenDuringCleanRebuild: true,
    incumbentTieBreakForbiddenDuringCleanRebuild: true,
    legacyReplacementHurdlesCannotChangePointZeroWinner: true,
    activeVsIndexCannotVetoMembershipUnlessMasterPromptExplicitlyAddsIt: true,
    leadershipIncumbentLabelsCannotCreateSelectionAdvantage: true,
    marketCapBonusForbidden: true,
    fameFamiliarityBonusForbidden: true,
    indexMembershipBonusForbidden: true,
    currentPortfolioStateCannotAffectMembership: true,
    externalChallengerStatusCreatesZeroScore: true,
    aestheticDiversificationQuotaForbidden: true,
    realCorrelatedRiskMustBeModeled: true,
    aiBaseCeilingCannotCreatePointZeroRankingPenalty: true,
    aiBaseCeilingCannotCreateNonAiDiversificationBonus: true,
    aiAbove30RequiresConditionalOverrideForDeliberateNewSizing: true,
    aiMomentumOverrideRequiresFullEvidenceStack: true,
    aiMomentumAloneCannotOverride: true,
    aiPassiveDriftAbove30CannotAutoSell: true,
    tapeRsCannotReplaceFundamentals: true,
    unknownDataMustReduceConfidence: true,
    researchCannotScoreDirectly: true,
    shadowSignalsHaveZeroDirectRankingAuthority: true,
    gateCannotBecomeBonus: true,
    stressTestCannotBePublishedAsForecast: true,
    syntheticCasesCannotCountAsRealEvaluationEvidence: true,
    criticalVariableMissingCannotBeSilentlyImputed: true,
    entityIdentityMustBeResolvedBeforeExtraction: true,
    worldStateMustRefreshBeforeMaterialAction: true,
    learningCannotModifyCanon: true,
    breadthCannotRescueCandidate: true,
    strategicCriticalityCannotCreatePointZeroSizeBias: true,
    deltaCannotConclude: true,
    deltaCannotModulateCoreConfidenceWhileShadow: true,
    kappaCannotChangeMethodology: true,
    gammaCannotBuySell: true,
    upsilonCannotAdmitExclude: true,
    rhoCannotBuySell: true,
    rhoCannotSetWeight: true,
    rhoCannotAdmitExclude: true,
    revealedCapitalCannotCreateDirectScore: true,
    revealedCapitalCannotBypassFundamentals: true,
    revealedCapitalCannotBypassValuation: true,
    revealedCapitalCannotBypassFalsifierVeto: true,
    traderIdentityCannotCreateDirectScore: true,
    traderIntelligenceCannotBuySell: true,
    traderIntelligenceCannotSetWeight: true,
    traderIntelligenceCannotBypassFundamentals: true,
    traderIntelligenceCannotBypassValuation: true,
    traderIntelligenceCannotBypassCompetitionForCapital: true,
    traderIntelligenceCannotBypassFalsifierVeto: true,
    traderDerivedRulesRequireAuthorRemovalTest: true,
    durableRevisionGapRequiresIndependentFundamentalEvidence: true,
    falsifierVetoIndependent: true,
    decisionSafetyIndependent: true,
  },
  mainSelectionSequence: [
    'CANONICAL_ENTITY_NORMALIZATION_AND_DEDUP_650_RAW_490_TICKERS_487_ENTITIES',
    'POINT_ZERO_ZERO_PRIOR_ADVANTAGE',
    'T0_ANTI_MEGACAP_DISCOVERY_GATE_OMEGA',
    'BROAD_UNIVERSE_SCREENING',
    'PRINCIPAL_OMEGA',
    'BUSINESS_QUALITY_OMEGA',
    'GROWTH_AND_REVISIONS_OMEGA',
    'PER_SHARE_ECONOMICS_OMEGA_V1',
    'OWNER_ECONOMICS_NORMALIZATION_OMEGA_V1',
    'DURABLE_REVISION_GAP_OMEGA_V1',
    'VALUATION_OMEGA',
    'EXPECTED_RETURN_3_6Y',
    'FCF_MARGINS_ROIC_BALANCE_SHEET',
    'MOAT_AND_DISRUPTION_RISK',
    'AI_VALUE_MIGRATION_WHEN_APPLICABLE',
    'AI_CAPITAL_FORMATION_WHEN_APPLICABLE',
    'EXPECTATION_GAP_OMEGA',
    'TAPE_RS_COMPLEMENTARY_ONLY',
    'MACRO_REGULATORY_GEOPOLITICAL_FINANCING_RISK',
    'FALSIFIERS_OMEGA',
    'ECONOMIC_COMPARABLE_DUELS',
    'CROSS_SECTOR_COMPETITION_FOR_CAPITAL_OMEGA',
    'CAPITAL_BLIND_WHOLE_PORTFOLIO_UTILITY_SELECTION',
    'FULLY_ENDOGENOUS_OPTIMAL_N',
    'HIDDEN_FACTOR_CONCENTRATION_AUDIT',
    'BULL_BASE_BEAR_SENSITIVITY',
    'ANTI_BIAS_AUDIT',
  ],
  executionOnlySequence: [
    'WORLD_STATE_REFRESH',
    'REAL_BROKER_RECONCILIATION',
    'AI_EXPOSURE_CONTROL_30_BASE_WITH_CONDITIONAL_MOMENTUM_OVERRIDE',
    'TAX_AND_TRANSACTION_FRICTION',
    'LEGACY_ANTI_CHURN_REPLACEMENT_HURDLES_IF_USED',
    'REPLACEMENT_HYSTERESIS',
    'POSITION_SIZING',
    'ENTRY_TIMING',
    'HUMAN_APPROVAL_FOR_MATERIAL_ACTION',
  ],
  aiCapexPreScoreSequence: [
    'T0_ANTI_MEGACAP_DISCOVERY_GATE_OMEGA',
    'T1_FUNDAMENTAL_HARD_GATES',
    'T2_FINANCING_QUALITY_GATE_OMEGA_V1',
    'T3_CIRCULAR_DEMAND_GATE_OMEGA_V1',
    'T4_QUALITY_ADJUSTED_BACKLOG_OMEGA_V1',
    'T5_CAPITAL_RISK_TRANSFER_ADVANTAGE_OMEGA_V1',
    'ATLAS_FUNDAMENTAL_SCORE',
  ],
  finalRule: 'NO_INTENTES_JUSTIFICAR_LA_CARTERA_QUE_YA_TENEMOS_INTENTA_DERROTARLA',
} as const;