export const ATLAS_PRIMARY_ENGINE_HIERARCHY = {
  version: '2026-09-05-v4.18.0',
  firstConstitutionalGate: 'T0_ANTI_MEGACAP_DISCOVERY_GATE_OMEGA_V1_1',
  firstAnalyticalEngine: 'GREEN_VERIFIED_CONTINUITY_OMEGA_V1_0',
  greenVerificationStack: ['GREEN_PROVIDER_QUORUM_OMEGA_V1_1', 'GREEN_CONTINUITY_OMEGA_V1_4'] as const,
  primaryEngine: 'PRINCIPAL_OMEGA',
  primaryRole: 'structural_selection_quality_growth_asymmetry',
  refinementEngines: [
    'GREEN_VERIFIED_CONTINUITY_OMEGA_V1_0', 'GREEN_PULSE_OMEGA', 'GREEN_BREADTH_OMEGA', 'RELATIVE_GREEN_OMEGA',
    'LEADERSHIP_BIAS_CONTROL_OMEGA_V1', 'SUCCESSOR_DETECTION_OMEGA_V1_1',
    'CONTRACT_ECONOMIC_EVIDENCE_NORMALIZER_OMEGA_V1', 'ORGANIC_GROWTH_DECOMPOSITION_OMEGA_V1',
    'BUSINESS_QUALITY_OMEGA', 'GROWTH_OMEGA', 'CAPEX_PRODUCTIVITY_OMEGA', 'PRICE_MARGIN_PASS_THROUGH_OMEGA_V1', 'ECONOMIC_THROUGHPUT_GATE_OMEGA_V1',
    'BASE_RATE_SURVIVORSHIP_GATE_OMEGA_V1', 'NARRATIVE_TO_NUMBERS_BRIDGE_OMEGA_V1',
    'REINVESTMENT_RUNWAY_ROIC_OMEGA_V1', 'PER_SHARE_ECONOMICS_OMEGA_V1', 'MOAT_MIGRATION_OMEGA_V1',
    'CAPITAL_ALLOCATION_QUALITY_OMEGA_V1', 'STRUCTURAL_TIER_PRIORITY_OMEGA_V1',
    'OWNER_ECONOMICS_NORMALIZATION_OMEGA_V1',
    'EXPECTED_CAGR_DRIVER_BRIDGE_OMEGA_V1', 'VALUATION_COMPRESSION_STRESS_OMEGA_V1',
    'VALUATION_METHOD_INTEGRITY_OMEGA_V1', 'VALUATION_OMEGA', 'EXTERNAL_VALUATION_CROSS_CHECK_OMEGA_V1',
    'RISK_OMEGA', 'TAIL_RISK_DIAGNOSTICS_OMEGA_V1', 'CONVEXITY_RUIN_GUARD_OMEGA_V1', 'ACTIVE_VS_INDEX_HURDLE_OMEGA_V1', 'PRE_MORTEM_INVERSION_OMEGA_V1',
    'GLOBAL_LIQUIDITY_TRANSMISSION_OMEGA_V2', 'SPECULATIVE_LIQUIDITY_CANARY_OMEGA_V1',
    'SOVEREIGN_LIQUIDITY_PLUMBING_OMEGA_V1', 'SOVEREIGN_GOLD_ACCUMULATION_OMEGA_V1',
    'INSTITUTIONAL_CAPITAL_ROTATION_OMEGA_V1_1', 'INSTITUTIONAL_CONVERGENCE_OMEGA_V1', 'ROTATION_EVENT_POLICY_OMEGA_V1', 'MONEY_ROTATION_OMEGA',
    'ENERGY_ROTATION_OMEGA', 'EUROPEAN_FRAGMENTATION_ENERGY_SECURITY_OMEGA_V1_1', 'EU_FISCAL_STRESS_OMEGA_V1',
    'CHINA_INDUSTRIAL_DISPLACEMENT_OMEGA_V1', 'GOOD_COMPANIES_CHEAP_OMEGA', 'HISTORICAL_DISLOCATION_OMEGA',
    'SPECIALIZED_ENGINES_OMEGA', 'SIZE_NEUTRAL_RETURN_RANKING_OMEGA_V1',
  ] as const,
  conditionalSpecializedEngines: [
    'AI_DEMAND_MONETIZATION_PROOF_OMEGA_V1',
    'NEOCLOUD_CUSTOMER_ACCEPTANCE_GATE_OMEGA_V1',
    'AI_CAPEX_PAYBACK_OMEGA_V2_1', 'AI_ECONOMIC_PROOF_EQUITY_MONETIZATION_OMEGA_V1_1',
    'AI_FINANCIAL_FRAGILITY_OMEGA_V1_1', 'AI_CREDIT_TRANSMISSION_OMEGA_V1',
    'GRID_BOTTLENECK_POWER_CAPTURE_OMEGA_V1',
    'SPECIALIZED_ECONOMICS_OMEGA_V1',
    'MARKET_TOP_RISK_OMEGA', 'MARKET_BOTTOM_DETECTION_OMEGA', 'ENTRY_TIMING_RETURN_AWARE_OMEGA_V2_2',
    'LIQUIDITY_SPREAD_GATE_OMEGA_V1_1', 'EXECUTION_SAFE_ENTRY_TIMING_OMEGA_V1_1',
    'EVENT_PRICING_OPTIONS_EXPECTATIONS_OMEGA_V1', 'SPECIAL_SITUATIONS_OMEGA_V1',
    'MARKET_CONTEXT_ROUTER_OMEGA_V1', 'PREDICTIVE_ENSEMBLE_OMEGA_V1',
  ] as const,
  auxiliaryLayers: [
    'WINNER_PRESERVATION_OMEGA_V1', 'OPTIONALITY_RESERVE_OMEGA_V1', 'CAPITAL_SAFETY_LEVERAGE_DISCIPLINE_OMEGA_V1',
    'GAMMA_VIGENCIA_OMEGA_V1_2', 'OMEGA_NE_POLICY_V1',
  ] as const,
  learningAndValidationEngines: [
    'COMPETITION_FOR_CAPITAL_OMEGA',
    'ANTI_CHURN_REPLACEMENT_HURDLE_OMEGA_V1',
    'RECOMMENDATION_PERFORMANCE_AUDIT_OMEGA_V1',
    'LIVE_MARKET_VALIDATION_OMEGA_V1',
    'QLIB_FACTOR_LIBRARY_OMEGA_V1',
    'FACTOR_FORGE_OMEGA_V1',
    'STATISTICAL_BACKTEST_FIREWALL_OMEGA_V1',
    'DRIFT_GUARD_OMEGA_V1',
    'AGENT_DISAGREEMENT_CONFIDENCE_OMEGA_V1',
    'DELTA_DIVERGENCE_OMEGA_V1',
    'CORE_CONFIDENCE_AGGREGATION_OMEGA_V1',
    'KAPPA_CALIBRATION_OMEGA_V1_1',
    'GAMMA_VIGENCIA_OMEGA_V1_2',
    'GAMMA_KAPPA_ASSURANCE_LEDGER_OMEGA_V1',
    'OMEGA_NE_POLICY_V1',
    'UPSILON_ALLOCATION_OMEGA_V1',
    'PORTFOLIO_RISK_UTILITY_RESEARCH_OMEGA_V1',
    'DIVIDENDOLOGY_EXTRACTION_OMEGA_V1',
    'MODEL_LEARNING_GOVERNANCE_OMEGA_V1',
  ] as const,
  transversalGates: [
    'T0_ANTI_MEGACAP_DISCOVERY_GATE_OMEGA_V1_1',
    'ANTI_DELUSION_CORE_OMEGA', 'EVIDENCE_INTEGRITY_OMEGA', 'SOURCE_AUTHENTICITY_OMEGA', 'QUANTITATIVE_INTEGRITY_OMEGA',
    'TEMPORAL_NORMALIZATION_OMEGA', 'VALUATION_METHOD_INTEGRITY_OMEGA_V1', 'SIZE_NEUTRALITY_AUDIT_OMEGA_V1', 'SYSTEMIC_CASCADE_OMEGA_V1',
    'CONVEXITY_RUIN_GUARD_OMEGA_V1', 'PRE_MORTEM_INVERSION_OMEGA_V1',
    'FALSIFIER_VETO_OMEGA_V1', 'LIQUIDITY_SPREAD_GATE_OMEGA_V1_1', 'DECISION_SAFETY_GATE_OMEGA',
  ] as const,
  rules: [
    'T0 ANTI-MEGACAP DISCOVERY GATE v1.1 is constitutional, prospective-only and precedes every ATLAS analytical, learning, Greek-contract, allocation and execution engine.',
    'T0 neutralizes discovery bias upstream: market cap, index membership, analyst coverage, brand familiarity and raw data availability contribute exactly zero to discovery priority and exactly zero to score.',
    'T0 does not penalize megacaps. A >$1T company may rank first after T0 when evidence-based economics, Expected Return and applicable gates justify it.',
    'T0 v1.1 audits five capitalization buckets before scoring: <$1B, $1-10B, $10-100B, $100B-1T and >$1T; the default policy requires two candidates per bucket when the tranche is large enough for the quota to apply.',
    'In CHALLENGER and NO-AI discovery, >$1T companies may not exceed 20% of the first discovery tranche under the current versioned T0 policy.',
    'Bucket quotas change discovery coverage only and never add or subtract company score.',
    'Index-only discovery universes are DISCOVERY_BIAS_DETECTED before downstream consumption.',
    'Historical discovery provenance is never reconstructed: legacy holdings with unknown origins are LEGACY_PROVENANCE_UNKNOWN and no retroactive size-neutral claim is made.',
    'Sparse reporting creates no T0 penalty. If a verified entity later becomes VIGENCIA_NO_EVALUABLE, OMEGA-NE handles uncertainty without converting opacity into poor quality or verified safety.',
    'Size-related saturation, runway, liquidity or execution-capacity effects are admissible only when demonstrated causally by economic evidence after T0; size itself is never proof.',
    'After integrity and ticker-identity normalization, canonical GREEN execution enters through GREEN VERIFIED CONTINUITY Ω, which runs Provider Quorum before GREEN classification.',
    'No caller may promote vendor performance labels, inferred percentages or unsynchronized observations directly into a GREEN score.',
    'GREEN requires 3 core providers per horizon; Trading 212 user evidence is an optional broker cross-check and never counts toward the core-provider minimum.',
    'GREEN 5/5 is the strongest continuity class and GREEN 4/5 is continuity-qualified; both still proceed through every other applicable ATLAS engine.',
    'GREEN 3/5 or lower never terminates the audit. Every registered/applicable engine continues and the weak GREEN state remains visible in the final evidence packet.',
    'GREEN is price-continuity evidence only: it is not fundamental evidence, verified capital flow, or final recommendation authority.',
    'PRINCIPAL OMEGA remains the structural selection engine after GREEN has been recorded.',
    'CONTRACT ECONOMIC EVIDENCE NORMALIZER forbids TAM, framework values, contract ceilings, milestone or warrant values, RPO, backlog, orders or shipments from being promoted directly into recognized revenue, FCF or DCF base cases.',
    'ORGANIC GROWTH DECOMPOSITION separates reported growth from M&A, FX, divestiture and accounting effects before Growth, Economic Proof or Expected Return consume the number.',
    'PRICE MARGIN PASS-THROUGH requires price, input cost, volume, gross margin and gross-profit confirmation; a price increase alone is not pricing power.',
    'STRUCTURAL TIER PRIORITY classifies S/A+/A/B+ independently from price and has no BUY/SELL, Expected Return or portfolio-weight authority.',
    'ECONOMIC THROUGHPUT GATE measures Demand -> Capture -> Conversion -> FCF -> ROIC; activity is not economic proof.',
    'Economic Proof validation is independent from GREEN, Price Matrix, drawdown, relative strength, flow and price response; market-data failure cannot erase valid fundamental proof.',
    'BASE RATE & SURVIVORSHIP requires failed comparables as well as winners; survivor-only hero stories are process-invalid.',
    'NARRATIVE TO NUMBERS requires a continuous TAM -> Customers -> Volume/Price -> Revenue -> Margin -> OCF -> FCF -> ROIC -> Per Share bridge; a missing stage caps the proof state.',
    'REINVESTMENT RUNWAY requires incremental ROIC above WACC plus credible runway; historical ROIC without reinvestment capacity is not compounding proof.',
    'PER-SHARE ECONOMICS separates enterprise growth from owner growth and treats dilution/SBC as economic leakage.',
    'MOAT MIGRATION audits forward durability; a current moat cannot be assumed permanent when workflow, data, regulation, network effects or AI substitution change.',
    'CAPITAL ALLOCATION QUALITY measures incremental ROIC, net diluted share count, distributions, acquisitions and leverage; buyback headlines alone are not owner accretion.',
    'CURRENT EARNINGS != NORMALIZED EARNINGS != DURABLE EARNINGS != OWNER EARNINGS; cyclicals and capital-intensity regime shifts must be normalized before valuation and Expected Return.',
    'PEAK EARNINGS PROBABILITY can disable spot P/E and TTM FCF yield as primary valuation inputs when margins, spreads, utilization or commodity economics are statistically elevated.',
    'EXPECTED CAGR DRIVER BRIDGE is diagnostic only and cannot replace canonical Bear/Base/Bull scenario Expected Return.',
    'VALUATION COMPRESSION STRESS tests whether a good business remains a good stock if the terminal multiple normalizes.',
    'CONVEXITY RUIN GUARD can veto attractive upside when permanent-loss, refinancing or forced-equity risk is unacceptable.',
    'ACTIVE VS INDEX HURDLE requires an active stock to demonstrate a meaningful expected-return advantage over the relevant passive alternative.',
    'ANTI-CHURN REPLACEMENT gives the incumbent the tie: absent a structural falsifier, replacement normally requires >=3pp net Expected CAGR advantage after verified friction or >=5 ATLAS score points.',
    'PRE-MORTEM & INVERSION is mandatory before high-conviction replacement and identifies unmitigated failure paths without inventing falsifiers.',
    'VALUATION METHOD INTEGRITY requires verified listing/currency/unit/price, selects archetype-compatible valuation methods and disables intrinsic-value scoring for pre-proof companies.',
    'Banks and insurers cannot be forced through generic corporate FCF/DCF heuristics when sector-specific capital and return metrics are the economically valid model.',
    'Material one-offs, mechanically pathological ROIC and capital-intensity regime shifts must be normalized before valuation feeds Expected Return.',
    'EXTERNAL VALUATION CROSS-CHECK has zero direct score weight: vendor fair value is diagnostic, never mechanically averaged with ATLAS Fair Value and never annualized into ATLAS CAGR without a compatible verified horizon.',
    'FALSIFIER VETO is independent and absolute: a confirmed structural falsifier overrides E-Proof, valuation and Expected Return.',
    'Unverified evidence cannot be promoted to a confirmed falsifier.',
    'Price is not evidence and a trigger is not a falsifier.',
    'SIZE-NEUTRAL RETURN RANKING starts every ticker at 0/1000; market cap and generic quality provide zero bonus and zero penalty.',
    'Growth Saturation may reduce expected-return opportunity only from economic evidence, never from size alone.',
    'ENTRY TIMING RETURN-AWARE credits the correction already observed before calculating any remaining pullback requirement.',
    'Current drawdown from ATH or rolling peak is preferred to a negative window return; window return is a fallback only when peak data are unavailable.',
    'No universal extra -3%, -5% or -10% correction may be demanded after ticker-specific dislocation bands are already reached.',
    'ENTRY TIMING PASS does not authorize an order until LIQUIDITY / SPREAD GATE verifies same-ticker, attributable and fresh bid/ask evidence.',
    'Protected limit placement may pass without asserting an immediate fill; market execution remains blocked outside the configured spread and premium budgets.',
    'AI DEMAND MONETIZATION PROOF must normalize run-rate versus realized TTM revenue and distinguish usage from paying/economically valuable demand.',
    'AI DEMAND MONETIZATION PROOF feeds demand/utilization evidence into AI CAPEX PAYBACK without double-counting.',
    'NEOCLOUD CUSTOMER ACCEPTANCE GATE is mandatory between Deployment and Revenue Recognition for material neocloud deployments; contract or deployment alone remains capped at E2.',
    'Customer acceptance strengthens execution proof but E3 still requires attributable recognized revenue plus credible margin.',
    'AI CAPEX PAYBACK must audit price-volume-cost elasticity: unit price declines are not payback failure unless volume, unit-cost and indirect monetization fail to offset them.',
    'AI ECONOMIC PROOF and AI EQUITY MONETIZATION are orthogonal: the business can capture AI value while the stock market refuses to reward it.',
    'AI EQUITY MONETIZATION may consume verified GREEN as market-behavior evidence; AI ECONOMIC PROOF may not consume GREEN as a proof input or validation dependency.',
    'AI EQUITY MONETIZATION forbids less-damaged or strong-RS stocks from being called CONFIRMED RECEIVER unless verified price continuity, flow, price response and proximity to Tmax also pass.',
    'PROOF_UP_MONETIZATION_DOWN is WATCH_FOR_REMONETIZATION by default and is never an automatic BUY.',
    'AI FINANCIAL FRAGILITY must separate recognized debt, recognized leases, non-commenced leases, purchase commitments and contingent/backstop exposure.',
    'AI FINANCIAL FRAGILITY and AI CREDIT TRANSMISSION remain independent from AI CAPEX PAYBACK and cannot double-count evidence.',
    'AI demand, AI CAPEX, AI revenue, AI FCF and AI owner return are separate states; AI Funding Quality and Time-to-Monetization must reconcile incremental ROIC against marginal funding cost.',
    'GRID BOTTLENECK POWER CAPTURE must normalize interconnection queues by stage; queued MW is never treated as firm load by itself.',
    'GRID BOTTLENECK POWER CAPTURE feeds Global CAPEX Chain and Power Owners but requires backlog/margin/FCF proof before economic capture is confirmed.',
    'PRICE RECEIVER != FLOW RECEIVER != CAPITAL RECEIVER != ATTRACTIVE INVESTMENT; lagged 13F or quarterly positioning never confirms current flow without independent current-flow evidence.',
    'Materials and mining must be decomposed at minimum into gold/precious, copper/base, uranium, rare earths, diversified mining and steel/metals before flow or economics are attributed.',
    'Refining uses normalized crack spreads, capture rates, throughput, operating costs and maintenance capital; oil price direction alone is not a refiner buy signal.',
    'Gold miners require Gold-to-Miner Transmission through realized price, AISC, CAPEX, taxes/royalties and FCF/share; gold price alone is not owner economics.',
    'Fundamental-Flow Divergence preserves the distinction between strong economics and weak market validation; flow deterioration alone is not a structural falsifier.',
    'NOMINAL RETURN != REAL WEALTH; Expected Return may be converted to real return after inflation and verified costs without replacing the canonical scenario model.',
    'Factor duplication and marginal portfolio contribution are evaluated before final Competition for Capital; a high standalone score does not create a free slot.',
    'W2_YELLOW_HIGH is a surveillance overlay, not a structural F3/F4 state and not a confirmed falsifier.',
    'SYSTEMIC CASCADE escalates only on temporally aligned multi-channel evidence and never emits a structural SELL by itself.',
    'WINNER PRESERVATION prevents automatic profit-taking solely because a validated leader has multiplied.',
    'RECOMMENDATION PERFORMANCE AUDIT preserves an immutable ex-ante T0 snapshot and never judges process quality from outcome alone.',
    'Recommendation Alpha and Selection Alpha are distinct: positive absolute return does not prove good capital allocation.',
    'LIVE MARKET VALIDATION compares LAST AUDIT -> NOW and keeps market validation orthogonal to fundamental validation.',
    'Rising price never creates verified institutional flow; absent flow evidence remains NOT_VERIFIED.',
    'QLIB / RD-AGENT / ALPHAFORGE inspired factor research has zero direct structural-score weight and begins in SHADOW.',
    'FACTOR FORGE may generate candidate formulas but no generated factor may skip point-in-time, survivorship, purged, embargo, walk-forward, cost and multiple-testing controls.',
    'STATISTICAL BACKTEST FIREWALL treats in-sample alpha as insufficient and PASS_SHADOW_ELIGIBLE as a research state, not canonical promotion.',
    'PREDICTIVE ENSEMBLE weights only traceable models with earned out-of-sample reliability; unavailable model outputs are never simulated, inferred or backfilled.',
    'PREDICTIVE ENSEMBLE is horizon-specific and orthogonal to structural quality, Expected Return 3-6Y, Falsifier Veto and broker execution authority.',
    'MARKET CONTEXT ROUTER may alter predictive model weights from regime-specific OOS evidence but may not rewrite company fundamentals.',
    'DRIFT GUARD may reduce or suspend a predictive model when distribution shift, RankIC decay or calibration deterioration is material.',
    'AGENT DISAGREEMENT preserves conflict as uncertainty; averaging agents cannot erase material disagreement or manufacture confidence.',
    'TAIL RISK DIAGNOSTICS adds CVaR, downside deviation, max drawdown, Ulcer Index, skew, excess kurtosis and tail ratio without creating standalone structural points.',
    'PORTFOLIO RISK UTILITY is research-only with explicit caller-defined risk aversion; lambda weights are not universal constants.',
    'DELTA DIVERGENCE is the canonical evaluator-disagreement contract: it requires >=3 independent passes on one aligned evidence graph and emits NO_MEDIBLE whenever independence is doubtful.',
    'DELTA measures global sigma/IQR and per-dimension disagreement only; it cannot conclude which evaluator is right or issue a decision.',
    'A DELTA proxy produced by the same model or by non-identical evidence subsets remains SHADOW only; it cannot modulate Core Confidence.',
    'CORE CONFIDENCE AGGREGATION owns the provisional mean(confidence)*exp(-k*D_OMEGA) bridge; k is versioned policy and can change only through governance supported by KAPPA evidence.',
    'KAPPA CALIBRATION v1.1 is event-sourced: CASE_SEALED is immutable and RESOLVED, INVALIDATED or REISSUED are new append-only events linked to the original case.',
    'KAPPA seals claim type, horizon, probability, resolution criteria, resolution source and emitter version; retrospective edits never overwrite the original preregistration.',
    'KAPPA reports Brier and Log Loss and computes Brier Skill Score by claim-type x horizon base rate; fifty cases unlock only a first verdict and never automatic methodology change.',
    'GAMMA VIGENCIA v1.2 accepts only falsifiers that are observable, causal and thesis-relevant and whose baseline is the latest published period available at seal time.',
    'GAMMA v1.2 rejects THRESHOLD_ALREADY_BREACHED and BASELINE_NON_STANDARD at ingestion; AMBER contributes factor 0.5 and RED factor 1.0 for non-critical falsifiers.',
    'GAMMA keeps continuous V_OMEGA separate from critical activation; NOT_EVALUATED never becomes NORMAL and V_OMEGA=1 means no deterioration relative to the sealed baseline, not thesis quality.',
    'ENTITY_IDENTITY_NOT_VERIFIED is a pre-GAMMA integrity block and cannot be converted into OMEGA-NE.',
    'OMEGA-NE is a versioned uncertainty policy: VIGENCIA_NO_EVALUABLE receives no quality penalty, no V_OMEGA substitute, a hard 2.0% equity-base position cap and Xi escalation after two consecutive opaque quarters.',
    'GAMMA/KAPPA assurance ledgers are append-only and event-sourced; prev_hash, sealed_at and record_hash are generated server-side under transactional advisory locks.',
    'Ledger UPDATE/DELETE is blocked and every chain can be recomputed; canonical sealing batches must additionally anchor the stream head hash in external GitHub Governance to detect privileged full-history rewrites.',
    'GAMMA thesis vigencia and DRIFT GUARD model-distribution drift are orthogonal and neither replaces the other.',
    'UPSILON ALLOCATION consumes only an admission set already closed by canonical decision authority; it cannot admit or exclude positions.',
    'UPSILON requires explicit Expected Return. Structural Score x Confidence x V_OMEGA is prohibited as an expected-return proxy.',
    'UPSILON treats position/theme caps as hard constraints and uses fractional thematic exposure: portfolio theme exposure = sum(weight_i * exposure_i).',
    'ACTIVE_ADMITTED positions preserve the configured minimum; ADMITTED_RESERVE may receive zero without being interpreted as exclusion.',
    'DIVIDENDOLOGY EXTRACTION is an external-method diagnostic with zero direct ATLAS score weight until broad out-of-sample validation proves incremental signal.',
    'DIVIDEND YIELD, Dividend Aristocrat labels and Dividend King labels earn zero ATLAS points; a non-dividend payer receives no penalty.',
    'SUSTAINABLE DISTRIBUTION DELTA = 5Y FCF CAGR - 5Y dividend CAGR is a diagnostic capital-allocation signal, not a BUY/SELL authority or structural falsifier by itself.',
    'DIVIDENDOLOGY EXTRACTION may reuse ROIC/runway, FCF, moat, capital allocation, valuation and institutional evidence only as cross-engine synthesis; those facts cannot be double-counted in the final score.',
    'MODEL LEARNING GOVERNANCE forbids recalibration from one stock or three isolated observations and requires broad, repeated, economically material, out-of-sample-supported evidence.',
    'HISTORICAL ALPHA does not imply FUTURE ALPHA; every accepted model change is versioned and auditable.',
  ] as const,
} as const;

export const ATLAS_CANONICAL_DECISION_SEQUENCE = [
  'INPUT',
  'T0_ANTI_MEGACAP_DISCOVERY_GATE_OMEGA_V1_1',
  'ANTI_DELUSION_CORE_OMEGA',
  'EVIDENCE_INTEGRITY_OMEGA',
  'SOURCE_AUTHENTICITY_OMEGA',
  'QUANTITATIVE_INTEGRITY_OMEGA',
  'TEMPORAL_NORMALIZATION_OMEGA',
  'GLOBAL_DISCOVERY_OMEGA',
  'GREEN_VERIFIED_CONTINUITY_OMEGA_V1_0',
  'GREEN_PULSE_OMEGA',
  'GREEN_BREADTH_OMEGA',
  'RELATIVE_GREEN_OMEGA',
  'LEADERSHIP_BIAS_CONTROL_OMEGA_V1',
  'PRINCIPAL_OMEGA',
  'SUCCESSOR_DETECTION_OMEGA_V1_1',
  'CONTRACT_ECONOMIC_EVIDENCE_NORMALIZER_OMEGA_V1',
  'ORGANIC_GROWTH_DECOMPOSITION_OMEGA_V1',
  'BUSINESS_QUALITY_OMEGA',
  'GROWTH_OMEGA',
  'CAPEX_PRODUCTIVITY_OMEGA',
  'PRICE_MARGIN_PASS_THROUGH_OMEGA_V1',
  'ECONOMIC_THROUGHPUT_GATE_OMEGA_V1',
  'BASE_RATE_SURVIVORSHIP_GATE_OMEGA_V1',
  'NARRATIVE_TO_NUMBERS_BRIDGE_OMEGA_V1',
  'REINVESTMENT_RUNWAY_ROIC_OMEGA_V1',
  'PER_SHARE_ECONOMICS_OMEGA_V1',
  'MOAT_MIGRATION_OMEGA_V1',
  'CAPITAL_ALLOCATION_QUALITY_OMEGA_V1',
  'STRUCTURAL_TIER_PRIORITY_OMEGA_V1',
  'OWNER_ECONOMICS_NORMALIZATION_OMEGA_V1',
  'VALUATION_METHOD_INTEGRITY_OMEGA_V1',
  'VALUATION_OMEGA',
  'EXTERNAL_VALUATION_CROSS_CHECK_OMEGA_V1',
  'EXPECTED_RETURN_3_6Y',
  'EXPECTED_CAGR_DRIVER_BRIDGE_OMEGA_V1',
  'VALUATION_COMPRESSION_STRESS_OMEGA_V1',
  'RISK_OMEGA',
  'TAIL_RISK_DIAGNOSTICS_OMEGA_V1',
  'CONVEXITY_RUIN_GUARD_OMEGA_V1',
  'GLOBAL_LIQUIDITY_TRANSMISSION_OMEGA_V2',
  'SPECULATIVE_LIQUIDITY_CANARY_OMEGA_V1',
  'SOVEREIGN_LIQUIDITY_PLUMBING_OMEGA_V1',
  'SOVEREIGN_GOLD_ACCUMULATION_OMEGA_V1',
  'INSTITUTIONAL_CAPITAL_ROTATION_OMEGA_V1_1',
  'INSTITUTIONAL_CONVERGENCE_OMEGA_V1',
  'ROTATION_EVENT_POLICY_OMEGA_V1',
  'MONEY_ROTATION_OMEGA',
  'ENERGY_ROTATION_OMEGA_WHEN_APPLICABLE',
  'EUROPEAN_FRAGMENTATION_ENERGY_SECURITY_OMEGA_WHEN_APPLICABLE',
  'EU_FISCAL_STRESS_OMEGA_WHEN_APPLICABLE',
  'CHINA_INDUSTRIAL_DISPLACEMENT_OMEGA_WHEN_APPLICABLE',
  'GOOD_COMPANIES_CHEAP_OMEGA_WHEN_APPLICABLE',
  'HISTORICAL_DISLOCATION_OMEGA_WHEN_APPLICABLE',
  'AI_DEMAND_MONETIZATION_PROOF_OMEGA_V1_WHEN_APPLICABLE',
  'NEOCLOUD_CUSTOMER_ACCEPTANCE_GATE_OMEGA_V1_WHEN_APPLICABLE',
  'AI_CAPEX_PAYBACK_OMEGA_V2_1_WHEN_APPLICABLE',
  'AI_ECONOMIC_PROOF_EQUITY_MONETIZATION_OMEGA_V1_1_WHEN_APPLICABLE',
  'AI_FINANCIAL_FRAGILITY_OMEGA_V1_1_WHEN_APPLICABLE',
  'AI_CREDIT_TRANSMISSION_OMEGA_V1_WHEN_APPLICABLE',
  'GRID_BOTTLENECK_POWER_CAPTURE_OMEGA_V1_WHEN_APPLICABLE',
  'SPECIALIZED_ECONOMICS_OMEGA_V1_WHEN_APPLICABLE',
  'SPECIALIZED_ENGINES_OMEGA_WHEN_APPLICABLE',
  'SYSTEMIC_CASCADE_OMEGA_V1',
  'WINNER_PRESERVATION_OMEGA_V1',
  'OPTIONALITY_RESERVE_OMEGA_V1',
  'ACTIVE_VS_INDEX_HURDLE_OMEGA_V1',
  'COMPETITION_FOR_CAPITAL_OMEGA',
  'PORTFOLIO_RISK_UTILITY_RESEARCH_OMEGA_V1',
  'ANTI_CHURN_REPLACEMENT_HURDLE_OMEGA_V1',
  'PRE_MORTEM_INVERSION_OMEGA_V1',
  'RECOMMENDATION_PERFORMANCE_AUDIT_OMEGA_V1',
  'LIVE_MARKET_VALIDATION_OMEGA_V1',
  'GAMMA_KAPPA_ASSURANCE_LEDGER_OMEGA_V1',
  'GAMMA_VIGENCIA_OMEGA_V1_2_WHEN_THESIS_REGISTERED',
  'OMEGA_NE_POLICY_V1_WHEN_GAMMA_NO_EVALUABLE',
  'QLIB_FACTOR_LIBRARY_OMEGA_V1',
  'FACTOR_FORGE_OMEGA_V1',
  'STATISTICAL_BACKTEST_FIREWALL_OMEGA_V1',
  'MARKET_CONTEXT_ROUTER_OMEGA_V1_WHEN_AVAILABLE',
  'DRIFT_GUARD_OMEGA_V1_WHEN_MODEL_AVAILABLE',
  'PREDICTIVE_ENSEMBLE_OMEGA_V1_WHEN_AVAILABLE',
  'AGENT_DISAGREEMENT_CONFIDENCE_OMEGA_V1_WHEN_AVAILABLE',
  'DELTA_DIVERGENCE_OMEGA_V1_WHEN_INDEPENDENT_PASSES_AVAILABLE',
  'CORE_CONFIDENCE_AGGREGATION_OMEGA_V1_WHEN_DELTA_MEDIBLE',
  'KAPPA_CALIBRATION_OMEGA_V1_1_WHEN_RESOLVED_LEDGER_AVAILABLE',
  'DIVIDENDOLOGY_EXTRACTION_OMEGA_V1',
  'MODEL_LEARNING_GOVERNANCE_OMEGA_V1',
  'SIZE_NEUTRAL_RETURN_RANKING_OMEGA_V1',
  'ENTRY_TIMING_RETURN_AWARE_OMEGA_V2_2',
  'LIQUIDITY_SPREAD_GATE_OMEGA_V1_1',
  'EXECUTION_SAFE_ENTRY_TIMING_OMEGA_V1_1',
  'SIZE_NEUTRALITY_AUDIT_OMEGA_V1',
  'FALSIFIER_VETO_OMEGA_V1',
  'UPSILON_ALLOCATION_OMEGA_V1_WHEN_ADMISSION_SET_CLOSED',
  'DECISION_SAFETY_GATE_OMEGA',
  'DECISION_LOG_OMEGA',
  'GITHUB_NOTION_PERSISTENCE',
] as const;
