import { MAX_PORTFOLIO_POSITIONS_V2, MIN_PORTFOLIO_POSITIONS_V2 } from './endogenous-portfolio-engine-v2';

export const ENDOGENOUS_PORTFOLIO_ENGINE_V2_CANON = {
  version: '2026-09-06-v2.1.0',
  hierarchyRollupTarget: '2026-09-06-v4.21.0',
  status: 'ACTIVE_CANONICAL',
  supersedes: 'ENDOGENOUS_PORTFOLIO_ENGINE_V2_2026_09_05_FOR_PORTFOLIO_OBJECTIVE_AND_CARDINALITY',
  preserves: [
    'T0_ANTI_MEGACAP_DISCOVERY_GATE_OMEGA_V1_1',
    'CAPITAL_BLIND_PORTFOLIO_SELECTION_LAW',
    'FALSIFIER_VETO_OMEGA_V1',
    'GAMMA_VIGENCIA_OMEGA_V1_2',
    'KAPPA_CALIBRATION_OMEGA_V1_1',
    'RHO_COUNTERPARTY_EXPOSURE_OMEGA_V1',
    'SELECTION_SIZING_TIMING_SEPARATION',
    'REPLACEMENT_FIREWALL_V2',
    'HYSTERESIS_OMEGA',
  ],
  minPositions: MIN_PORTFOLIO_POSITIONS_V2,
  maxPositions: MAX_PORTFOLIO_POSITIONS_V2,
  optimalN: 'ENDOGENOUS_WITHOUT_DIVERSIFICATION_QUOTA',
  selectionTestWeights: 'EQUAL_1_OVER_N_ONLY',
  globalOptimalityClaim: false,
  searchMode: 'DETERMINISTIC_LOCAL_SEARCH',
  laws: [
    'MAX RETURN / LOW VOL IS INVIOLABLE: maximize expected return subject to modeled volatility, permanent-loss, tail and fragility risk.',
    'PORTFOLIO > TICKER: portfolio membership is decided by whole-set return/risk utility, never by ticker score alone.',
    'Sector, geography, style, market-cap bucket and aesthetic balance have zero membership authority and zero quota authority.',
    'A portfolio may be heavily concentrated in one or two sectors when those names dominate return/risk utility.',
    'Diversification has zero standalone utility. It matters only when it demonstrably reduces modeled risk without sacrificing enough expected return to lower whole-portfolio utility.',
    'Causal Redundancy and driver coverage remain diagnostic fields; neither can independently penalize, reward, force or rescue membership.',
    'Required structural-driver coverage and missing-driver exceptions are forbidden in canonical selection.',
    'Financing Correlation remains admissible only as a common-fragility risk input, not as a diversification aesthetic.',
    'Market cap, fame, current invested capital, current position weight, personal P/L, personal average cost and incumbent status have zero clean-selection authority.',
    'Capital-Blind is not Price-Blind: valuation and explicit Expected Return remain legitimate economic inputs.',
    'Expected Return is decomposed into fundamental growth, cash yield, capital returns and multiple normalization; isolated P/E is not an Expected Return engine.',
    'Scenario Matrix and robustness remain admissible only as risk measurement.',
    'Canonical operating risk weights are versioned at Permanent Loss 40%, Tail Risk 20%, Volatility 40%; they are policy parameters, not universal constants.',
    'Portfolio selection uses neutral equal test weights 1/N; these weights are deleted conceptually after membership is chosen and never become Position Sizing.',
    'Cardinality is endogenous from N=1 to the default search ceiling N=50; no minimum number of positions may be justified by diversification.',
    'A tiny positive ΔU is insufficient: marginal utility must exceed a versioned economic-materiality threshold.',
    'CORE_ROBUSTNESS is legitimate only when modeled risk reduction improves total return/risk utility; never because a sector or driver is missing.',
    'Anti-Dilution rejects additional positions that dilute stronger ideas without enough return/risk improvement.',
    'Replacement Firewall uses ΔU = U(P-i+j)-U(P), not score difference alone and not sector balancing.',
    'Hysteresis is state-dependent: GREEN incumbents require the largest material improvement, ORANGE less, RED is near-open.',
    'Confidence remains separate from score and Expected Return; lower confidence creates uncertainty cost but never rewrites ER.',
    'Final classification remains CORE_ALPHA / CORE_ROBUSTNESS / COMPLEMENTARY_ALPHA / BORDERLINE / REDUNDANT / REJECTED.',
    'The deterministic local-search implementation is a best-known heuristic and MUST NOT be described as proof of the global combinatorial optimum.',
  ],
} as const;
