export const ENDOGENOUS_PORTFOLIO_ENGINE_V2_CANON = {
  version: '2026-09-06-v2.2.0',
  status: 'ACTIVE_SUBORDINATE_ENGINE',
  masterAuthority: 'docs/canon/ATLAS_OMEGA_MASTER_PROMPT_CANONICAL.md',
  universeVersion: 'ATLAS_CORE_650_RAW_490_UNIQUE_487_ENTITY_2026-09-06',
  supersedes: 'ENDOGENOUS_PORTFOLIO_ENGINE_V2_2026_09_06_V2_1_FOR_CARDINALITY_POLICY',
  preserves: [
    'T0_ANTI_MEGACAP_DISCOVERY_GATE_OMEGA',
    'CAPITAL_BLIND_PORTFOLIO_SELECTION_LAW',
    'FALSIFIER_VETO_OMEGA_V1',
    'GAMMA_VIGENCIA_OMEGA_V1_2',
    'KAPPA_CALIBRATION_OMEGA_V1_1',
    'RHO_COUNTERPARTY_EXPOSURE_OMEGA_V1',
    'SELECTION_SIZING_TIMING_SEPARATION',
    'REPLACEMENT_FIREWALL_V2_EXECUTION_ONLY',
    'HYSTERESIS_OMEGA_EXECUTION_ONLY',
  ],
  cardinalityBounds: 'NONE',
  optimalN: 'FULLY_ENDOGENOUS_FROM_POINT_ZERO_MARGINAL_PORTFOLIO_UTILITY',
  selectionTestWeights: 'EQUAL_1_OVER_N_ONLY',
  globalOptimalityClaim: false,
  searchMode: 'DETERMINISTIC_LOCAL_SEARCH',
  laws: [
    'MASTER UNIVERSE PROMPT is the sole authority for clean rebuild, ranking, membership and OPTIMAL_N.',
    'All canonical economic entities start at Point Zero with zero prior advantage.',
    'Duplicate raw appearances are deduplicated before portfolio competition; duplicate rows never create extra selection opportunities.',
    'MAX RETURN / LOW VOL IS INVIOLABLE: maximize expected return subject to modeled volatility, permanent-loss, tail and fragility risk.',
    'PORTFOLIO > TICKER: portfolio membership is decided by whole-set return/risk utility, never by ticker score alone.',
    'Sector, geography, style, market-cap bucket and aesthetic balance have zero membership authority and zero quota authority.',
    'A portfolio may be heavily concentrated when those names dominate return/risk utility.',
    'Diversification has zero standalone utility. It matters only when it demonstrably reduces modeled risk enough to improve whole-portfolio utility.',
    'Causal Redundancy and driver coverage remain diagnostics; neither can independently penalize, reward, force or rescue membership.',
    'Required structural-driver coverage and missing-driver exceptions are forbidden in canonical selection.',
    'Financing Correlation remains admissible only as a common-fragility risk input, not as a diversification aesthetic.',
    'Market cap, fame, current invested capital, current position weight, personal P/L, personal average cost and incumbent status have zero clean-selection authority.',
    'Capital-Blind is not Price-Blind: valuation and explicit Expected Return remain legitimate economic inputs.',
    'Expected Return is decomposed into fundamental growth, cash yield, capital returns and multiple normalization; isolated P/E is not an Expected Return engine.',
    'Scenario Matrix and robustness remain admissible only as risk measurement.',
    'Canonical operating risk weights are versioned at Permanent Loss 40%, Tail Risk 20%, Volatility 40%; they are policy parameters, not universal constants.',
    'Portfolio selection uses neutral equal test weights 1/N; these weights never become Position Sizing.',
    'There is no ex-ante minimum, maximum, target or preferred position count. No 20/25/30/32/35/37/50 authority survives.',
    'Start from the empty Point-Zero portfolio and expand only while the best next portfolio cardinality improves return/risk utility.',
    'Stop expansion at the first N+1 that fails the non-negative canonical marginal-utility threshold; no fixed-N or aesthetic exception is permitted.',
    'CORE_ROBUSTNESS is legitimate only when modeled risk reduction improves total return/risk utility; never because a sector or driver is missing.',
    'Anti-Dilution rejects additional positions that dilute stronger ideas without enough return/risk improvement.',
    'Replacement Firewall and Hysteresis are execution-transition controls only. They cannot bias the clean Point-Zero rebuild toward incumbents.',
    'Confidence remains separate from score and Expected Return; lower confidence creates uncertainty cost but never rewrites ER.',
    'Final classification remains CORE_ALPHA / CORE_ROBUSTNESS / COMPLEMENTARY_ALPHA / BORDERLINE / REDUNDANT / REJECTED.',
    'The deterministic local-search implementation is a best-known heuristic and MUST NOT be described as proof of the global combinatorial optimum.',
    'No intentes justificar la cartera que ya tenemos. Intenta derrotarla.',
  ],
} as const;