import { MAX_PORTFOLIO_POSITIONS_V2, MIN_PORTFOLIO_POSITIONS_V2 } from './endogenous-portfolio-engine-v2';

export const ENDOGENOUS_PORTFOLIO_ENGINE_V2_CANON = {
  version: '2026-09-05-v2.0.0',
  hierarchyRollupTarget: '2026-09-05-v4.20.0',
  status: 'ACTIVE_CANONICAL',
  supersedes: 'CAPITAL_BLIND_PORTFOLIO_SELECTION_OMEGA_V1_FOR_SET_OPTIMIZATION_ONLY',
  preserves: [
    'T0_ANTI_MEGACAP_DISCOVERY_GATE_OMEGA_V1_1',
    'CAPITAL_BLIND_PORTFOLIO_SELECTION_LAW',
    'FALSIFIER_VETO_OMEGA_V1',
    'GAMMA_VIGENCIA_OMEGA_V1_2',
    'KAPPA_CALIBRATION_OMEGA_V1_1',
    'RHO_COUNTERPARTY_EXPOSURE_OMEGA_V1',
    'SELECTION_SIZING_TIMING_SEPARATION',
  ],
  minPositions: MIN_PORTFOLIO_POSITIONS_V2,
  maxPositions: MAX_PORTFOLIO_POSITIONS_V2,
  optimalN: 'ENDOGENOUS',
  selectionTestWeights: 'EQUAL_1_OVER_N_ONLY',
  globalOptimalityClaim: false,
  searchMode: 'DETERMINISTIC_LOCAL_SEARCH',
  laws: [
    'PORTFOLIO > TICKER: portfolio membership is decided by set utility, never by ticker score alone.',
    'Market cap, fame, current invested capital, current position weight, personal P/L, personal average cost and incumbent status have zero clean-selection authority.',
    'Capital-Blind is not Price-Blind: valuation and explicit Expected Return remain legitimate economic inputs.',
    'Expected Return is decomposed into fundamental growth, cash yield, capital returns and multiple normalization; isolated P/E is not an Expected Return engine.',
    'Causal Redundancy is measured from causal-driver vectors, not only market-price correlation or GICS labels.',
    'Financing Correlation is a distinct fragility dimension for shared funding sources/counterparties.',
    'Scenario Matrix uses structural shocks rather than historical volatility alone.',
    'Permanent loss risk dominates volatility in the default versioned risk policy.',
    'Portfolio selection uses neutral equal test weights 1/N; these weights are deleted conceptually after membership is chosen and never become Position Sizing.',
    'Best-known portfolio sets are evaluated for every N from 20 through 35; N is chosen at the material marginal-utility knee subject to missing-driver robustness exception.',
    'A tiny positive ΔU is insufficient: marginal utility must exceed a versioned economic-materiality threshold.',
    'Alpha contribution and structural-robustness contribution are separate legitimate routes to membership.',
    'Anti-Dilution rejects additional positions that dilute higher-return ideas without material robustness/diversification benefit.',
    'Replacement Firewall uses ΔU = U(P-i+j)-U(P), not score difference alone.',
    'Hysteresis is state-dependent: GREEN incumbents require the largest material improvement, ORANGE less, RED is near-open.',
    'Confidence remains separate from score and Expected Return; lower confidence creates uncertainty cost but never rewrites ER.',
    'Final classification is CORE_ALPHA / CORE_ROBUSTNESS / COMPLEMENTARY_ALPHA / BORDERLINE / REDUNDANT / REJECTED.',
    'The deterministic local-search implementation is a best-known heuristic and MUST NOT be described as proof of the global combinatorial optimum.',
  ],
} as const;
