import { decisionSafetyGate, assertMoneyRotationSemantics } from '../evidence-ingestion/integrity';

export const EVIDENCE_INTEGRITY_OMEGA_V1_1 = {
  id: 'EVIDENCE_INTEGRITY_OMEGA_V1_1',
  status: 'canonical_candidate',
  mobileFirst: true,
  rules: [
    'MARKET_CAP_CHANGE is never CAPITAL_FLOW.',
    'Price return, market-cap change and AUM change cannot be published as money inflow/outflow.',
    'Level 2 evidence may trigger WATCH but cannot modify canonical state without Level 1 confirmation.',
    'Claims from the same causal event cluster count as one signal.',
    'A newly filed document is not necessarily new economic information.',
    'Conflicting equivalent quantitative observations require reconciliation before use.',
    'REDUCE or SELL requires a confirmed thesis falsifier with traceable primary evidence.',
  ] as const,
  gates: { moneyRotation: assertMoneyRotationSemantics, decision: decisionSafetyGate },
} as const;

export const ATLAS_CANONICAL_PIPELINE_V1_1 = [
  'MOBILE_INPUT',
  'EVIDENCE_INGESTION_OMEGA_V1',
  'SOURCE_AUTHENTICITY_OMEGA',
  'CLAIM_EXTRACTION_OMEGA',
  'QUANTITATIVE_SEMANTICS_OMEGA',
  'TEMPORAL_NORMALIZATION_OMEGA',
  'CROSS_SOURCE_VERIFICATION_OMEGA',
  'EVENT_DEDUP_SIGNAL_INDEPENDENCE_OMEGA',
  'VALIDATION_HARNESS_OMEGA',
  'EPISTEMIC_CLASSIFICATION',
  'THESIS_FALSIFIER_MAPPING_OMEGA',
  'GLOBAL_DISCOVERY',
  'MARKET_FILTERS',
  'BUSINESS_QUALITY_OMEGA',
  'GROWTH_OMEGA',
  'CAPEX_PRODUCTIVITY_OMEGA',
  'MONEY_ROTATION_OMEGA',
  'HISTORICAL_DISLOCATION_OMEGA',
  'CONSPIRACIONES_ATLAS',
  'NARRATIVE_SATURATION_OMEGA',
  'PHOENIX_2026_MONITOR_OMEGA',
  'VALUATION_OMEGA',
  'RISK_OMEGA',
  'CATALYSTS_OMEGA',
  'DECISION_SAFETY_GATE_OMEGA',
  'FINAL_SCORE_OMEGA',
  'DECISION_LOG_OMEGA',
] as const;