import {
  GURUS_FUNDS_OMEGA_MANIFEST,
  GURUS_FUNDS_SCORE_WEIGHTS,
  assessGurusFundsCandidate,
  calculateGurusFundsScore,
  classifyGuruSignalState,
  rankGurusFundsCandidates,
} from '../gurus-funds/engine';

export const GURUS_FUNDS_OMEGA_V1 = {
  ...GURUS_FUNDS_OMEGA_MANIFEST,
  scoreWeights: GURUS_FUNDS_SCORE_WEIGHTS,
  managerUniverse: [
    'Berkshire Hathaway / Warren Buffett',
    'Thiel Macro / Peter Thiel',
    'Duquesne Family Office / Stanley Druckenmiller',
    'Appaloosa / David Tepper',
    'Pershing Square / Bill Ackman',
    'Baupost / Seth Klarman',
    'Scion / Michael Burry',
    'Himalaya Capital / Li Lu',
    'Dalal Street / Mohnish Pabrai',
    'Aquamarine / Guy Spier',
    'Akre Capital / Chuck Akre',
    'TCI / Chris Hohn',
    'Fundsmith / Terry Smith',
    'Soros Fund Management',
    'Oaktree / Howard Marks',
  ] as const,
  states: [
    'WEAK_SIGNAL',
    'NEUTRAL',
    'DISCOVERY',
    'ACCUMULATION',
    'SMART_MONEY_CONVERGENCE',
    'STRONG_GURU_CONVICTION',
  ] as const,
  outputs: [
    'GURU_CONVICTION_OMEGA',
    'SMART_MONEY_CONVERGENCE_OMEGA',
    'NEW_POSITION_OMEGA',
    'ACCUMULATION_OMEGA',
    'DISTRIBUTION_OMEGA',
    'CONTRARIAN_OMEGA',
  ] as const,
  downstreamGates: [
    'ECONOMIC_PROOF',
    'QUALITY_OMEGA',
    'VALUATION_EXPECTED_RETURN',
    'FALSIFIERS_OMEGA',
  ] as const,
  rules: [
    'Run independently from Principal Omega, Good Companies Cheap Omega, Historical Dislocation/Burry Omega and Money Rotation Omega.',
    'Do not convert ownership, holder count or a 13F purchase into a portfolio BUY.',
    'Weight conviction and concentration more heavily than raw holder count.',
    'Reward cross-style convergence among independent managers and preserve contradictory flows as divergence.',
    'Treat 13F information as delayed and incomplete; it does not show a manager full economic exposure.',
    'Never state estimated purchase ranges as exact cost basis unless primary evidence proves the actual transaction price.',
    'Downweight highly diversified or high-turnover multi-strategy managers unless position size and persistence make the signal exceptional.',
    'Every candidate handed off by this engine must pass Economic Proof, Quality, Valuation/Expected Return and Falsifiers Omega.',
  ] as const,
  calculateScore: calculateGurusFundsScore,
  classifyState: classifyGuruSignalState,
  assess: assessGurusFundsCandidate,
  rank: rankGurusFundsCandidates,
} as const;
