import {
  INSTITUTIONAL_CAPITAL_ROTATION_MANIFEST,
  INSTITUTIONAL_FLOW_SCORE_WEIGHTS,
  assessInstitutionalRotation,
  calculateInstitutionalFlowScore,
  classifyInstitutionalFlowState,
  detectCapitalFlowDivergence,
  detectDistributionWarning,
} from '../institutional-rotation/engine';

export const INSTITUTIONAL_CAPITAL_ROTATION_OMEGA_V1 = {
  ...INSTITUTIONAL_CAPITAL_ROTATION_MANIFEST,
  scoreWeights: INSTITUTIONAL_FLOW_SCORE_WEIGHTS,
  states: [
    'NO_FLOW',
    'NEUTRAL',
    'EARLY_ROTATION',
    'INSTITUTIONAL_ACCUMULATION_PROBABLE',
    'CONFIRMED_RECEIVER',
    'STRONG_CAPITAL_ROTATION',
  ] as const,
  rules: [
    'Run independently from MONEY_ROTATION_OMEGA; neither engine overwrites the other.',
    'Use sector, subsector, factor and region as first-class rotation entities before selecting ticker beneficiaries.',
    'MARKET_CAP_CHANGE is never CAPITAL_FLOW.',
    'Price and volume may create an early warning but cannot alone produce CONFIRMED_RECEIVER.',
    'CONFIRMED_RECEIVER requires real fund/ETF flow evidence or an independent institutional positioning signal.',
    'Capital Flow Divergence Omega searches for flows and breadth improving before price confirmation.',
    'A positive FLOW_PRICE_DIVERGENCE is a WATCH_PRIORITY research state, never an automatic BUY.',
    'Technology rotation resolution requires persistent fund-flow improvement plus breadth improvement plus relative-strength repair; one mega-cap or one earnings gap cannot confirm the rotation.',
    'For the AI chain, preferred confirmation sequence is fund inflow -> semiconductor breadth improvement -> RS vs SPY repair -> NVDA/AVGO/ASML/AMAT confirmation -> propagation from C1/C2 toward C10-C13.',
    'If NVDA or another major catalyst beats but semiconductor breadth and RS fail to improve, treat that as negative evidence for broad AI equity monetization rather than confirmation.',
    'Hard-asset price leadership without direct fund-flow evidence remains INSTITUTIONAL_ACCUMULATION_PROBABLE, not CONFIRMED_RECEIVER.',
    'Distribution Warning Omega searches for price still rising while breadth and flows deteriorate.',
    'Price rising while verified fund flows fall is NEGATIVE_FLOW_DIVERGENCE and should reduce research priority until flows reverse, even if the sector remains green.',
    'After sector confirmation, identify 3-5 liquid ticker beneficiaries and hand them to the relevant ATLAS selection engine.',
    'This engine emits research/rotation state only; it cannot issue a portfolio BUY or SELL order by itself.',
    'Every daily execution must compare current score/state with prior observations to measure lead/lag and detection latency.',
  ] as const,
  currentCalibration20260822: {
    hardAssets: 'CONFIRMED_LEADERSHIP',
    materials: 'INSTITUTIONAL_ACCUMULATION_PROBABLE',
    technologyAI: 'FLOW_PRICE_DIVERGENCE_EARLY_ROTATION_WATCH',
    financials: 'NEGATIVE_FLOW_DIVERGENCE',
    portfolioAction: 'NO_PORTFOLIO_CHANGE',
    keyResolutionEvent: 'NVDA_Q2_FY27_2026_08_26',
  } as const,
  calculateScore: calculateInstitutionalFlowScore,
  classifyState: classifyInstitutionalFlowState,
  assess: assessInstitutionalRotation,
  detectCapitalFlowDivergence,
  detectDistributionWarning,
} as const;
