import { LEADERSHIP_BIAS_CONTROL_OMEGA_V1 } from './leadership-bias-control-omega';

export const LEADERSHIP_BIAS_CONTROL_OMEGA_REGISTRY = {
  engine: LEADERSHIP_BIAS_CONTROL_OMEGA_V1,
  placement: 'BIAS_CONTROL_AFTER_GLOBAL_DISCOVERY_BEFORE_FINAL_RANKING',
  dependencies: [
    'GLOBAL_DISCOVERY_OMEGA',
    'BUSINESS_QUALITY_OMEGA',
    'GROWTH_OMEGA',
    'CAPEX_PRODUCTIVITY_OMEGA',
    'INSTITUTIONAL_CAPITAL_ROTATION_OMEGA_V1',
    'MONEY_ROTATION_OMEGA_V1_3',
    'VALUATION_OMEGA',
    'RISK_OMEGA',
    'ENTRY_TIMING_OMEGA',
    'DECISION_SAFETY_GATE_OMEGA',
  ] as const,
  invariants: [
    'NO_SIZE_REWARD',
    'NO_SIZE_PENALTY_ALONE',
    'NO_FAME_REWARD',
    'NO_MOMENTUM_ONLY_PROMOTION',
    'NO_AUTOMATIC_PORTFOLIO_ORDER',
    'FORCE_INCUMBENT_VS_CHALLENGER_COMPARISON',
  ] as const,
} as const;
