import {
  MAX_PORTFOLIO_POSITIONS,
  MIN_PORTFOLIO_POSITIONS,
} from './capital-blind-portfolio-selection-omega';

export const ATLAS_PORTFOLIO_SELECTION_CANON = {
  version: '2026-09-05-v1.0.0',
  hierarchyRollupVersion: '2026-09-05-v4.19.0',
  engine: 'CAPITAL_BLIND_PORTFOLIO_SELECTION_OMEGA_V1',
  minPositions: MIN_PORTFOLIO_POSITIONS,
  maxPositions: MAX_PORTFOLIO_POSITIONS,
  optimalN: 'ENDOGENOUS',
  upstream: [
    'T0_ANTI_MEGACAP_DISCOVERY_GATE_OMEGA_V1_1',
    'HARD_GATES',
    'EXPECTED_RETURN_3_6Y',
    'PERMANENT_LOSS_RISK',
    'FINANCING_QUALITY_AND_CIRCULAR_DEMAND_WHEN_APPLICABLE',
    'EXPECTATION_GAP',
    'COMPETITION_FOR_CAPITAL_OMEGA',
  ],
  downstream: [
    'REPLACEMENT_FIREWALL_FOR_EXECUTABLE_TRANSITIONS_ONLY',
    'UPSILON_ALLOCATION_OMEGA_V1',
    'ENTRY_TIMING_RETURN_AWARE_OMEGA_V2_2',
  ],
  prohibitedSelectionInputs: [
    'CURRENT_INVESTED_EUR',
    'CURRENT_POSITION_WEIGHT',
    'PERSONAL_PNL',
    'PERSONAL_AVERAGE_COST',
    'CURRENT_PORTFOLIO_CAPITAL_BASE',
    'INCUMBENCY_BONUS',
  ],
  invariants: [
    'MARKET_CAP_AND_CURRENT_OWNERSHIP_HAVE_ZERO_SELECTION_AUTHORITY',
    'VALUATION_AND_EXPECTED_RETURN_REMAIN_VALID_SELECTION_INPUTS',
    'NO_FIXED_TARGET_COUNT_INSIDE_20_TO_35',
    'DO_NOT_FILL_TO_35_WITH_NON_POSITIVE_MARGINAL_UTILITY',
    'DO_NOT_EJECT_A_POSITIVE_MARGINAL_CONTRIBUTOR_TO_HIT_AN_ARBITRARY_25_OR_30',
    'SELECTION_DOES_NOT_EMIT_TARGET_WEIGHTS',
    'SELECTION_DOES_NOT_EMIT_ENTRY_TIMING',
  ],
} as const;
