import { PRE_CONSENSUS_DISCOVERY_OMEGA_VERSION } from './pre-consensus-discovery-omega';

export const ATLAS_PRE_CONSENSUS_DISCOVERY_CANON = {
  version: PRE_CONSENSUS_DISCOVERY_OMEGA_VERSION,
  status: 'ACTIVE_SHADOW_OOS_REQUIRED',
  parentSystem: 'OPEN_SOURCE_QUANT_AI_OMEGA_V1',
  placement: {
    after: ['T0_ANTI_MEGACAP_DISCOVERY_GATE_OMEGA_V1_1', 'BUSINESS_QUALITY_OMEGA', 'EXPECTED_RETURN_3_6Y'],
    beforePromotion: ['STATISTICAL_BACKTEST_FIREWALL_OMEGA_V1', 'MODEL_LEARNING_GOVERNANCE_OMEGA_V1'],
    portfolioAuthorityRemains: 'CAPITAL_BLIND_PORTFOLIO_SELECTION_OMEGA_V1',
  },
  childEngines: [
    'FUNDAMENTAL_TRAJECTORY_OMEGA_V1',
    'ATTENTION_GAP_OMEGA_V1',
    'INSTITUTIONAL_RECOGNITION_GAP_OMEGA_V1',
    'RECOGNITION_VELOCITY_OMEGA_V1',
    'PRE_CONSENSUS_DISCOVERY_OMEGA_V1',
  ],
  invariants: [
    'DIRECT_ATLAS_SCORE_WEIGHT_ZERO',
    'OBSCURITY_NEVER_ALPHA_BY_ITSELF',
    'NO_OVERRIDE_T0',
    'NO_OVERRIDE_HARD_GATES',
    'NO_OVERRIDE_FALSIFIER_VETO',
    'NO_OVERRIDE_CAPITAL_BLIND_SELECTION',
    'NO_OVERRIDE_ENDOGENOUS_N',
  ],
} as const;
