export const REVERSE_SCREENER_DISCOVERY_OMEGA_REGISTRY = {
  version: '2026-09-09-v1.1.0',
  status: 'ACTIVE_CANONICAL_RESEARCH_DISCOVERY',
  module: 'REVERSE_SCREENER_DISCOVERY_OMEGA_V1_1',
  implementationCommit: '4cb732c6402ce0990b6d4b94fb447cf93460ea1b',
  insertion: 'R0_DISCOVERY_BEFORE_E1_FULL_EVIDENCE_AND_BEFORE_CAPITAL_SELECTION',
  directCapitalAuthority: false,
  scoreWeights: {
    fundamentalAcceleration: 0.25,
    qualityTrend: 0.20,
    fcfQuality: 0.15,
    sectorRelativeValuation: 0.15,
    sectorRelativeMomentum: 0.15,
    dseSignal: 0.10,
  } as const,
  gates: {
    marketCapUsdBnMin: 2,
    requiresUsListing: true,
    excludesPreRevenueBiotech: true,
    excludesSpac: true,
    excludesMicroCapFinancials: true,
    acceleration: 'AT_LEAST_ONE_TIER_A_AND_ONE_TIER_B',
    valuation: 'AT_LEAST_TWO_OF_THREE',
    operatingMarginSectorPercentileMinExclusive: 40,
    netDebtToEbitdaSectorPercentileMaxExclusive: 40,
    requiresRoicAboveEstimatedWacc: true,
    requiresPriceAboveMa200: true,
    rsVsSector3mPpMinExclusive: 0,
    rsVsSector6mPpMinExclusive: -5,
    netDebtToEbitdaHardVetoAbove: 4,
    dseZActivationThreshold: 2,
  } as const,
  penalties: {
    customerConcentrationPctAbove30: -15,
    gaapNonGaapGapPctAbove25: -10,
    regulatoryRevenuePctAbove50: -20,
    cycleNormalizationRequired: -10,
    materialLitigation: 'MANUAL_REVIEW_FLAG_ONLY',
  } as const,
  dataPipelineStatus: 'LOGIC_DEFINED_PIPELINE_NOT_YET_OPERATIONAL',
  openDataDecisions: [
    'OPEN_01_MULTI_SECTOR_CLASSIFICATION',
    'OPEN_02_SMALL_SECTOR_PERCENTILE_FALLBACK',
    'OPEN_03_WACC_ERP_ASSUMPTION',
    'OPEN_04_PRIMARY_FINANCIAL_DATA_SOURCE',
    'OPEN_05_SECTOR_PERCENTILE_REFRESH_TRIGGER',
  ] as const,
  invariants: [
    'DISCOVERY_SCORE_NEVER_BUY_ALONE',
    'DISCOVERY_SCORE_NEVER_PORTFOLIO_WEIGHT',
    'ACCELERATION_REQUIRES_TIER_A_AND_TIER_B',
    'VALUATION_REQUIRES_TWO_OF_THREE',
    'SECTOR_RELATIVE_THRESHOLDS_PRECEDE_RAW_ABSOLUTE_THRESHOLDS',
    'MOMENTUM_IS_RELATIVE_TO_SECTOR',
    'DSE_IS_DYNAMIC_SENSOR_NOT_BUSINESS_EVIDENCE',
    'CATALYST_IS_MANUAL_ATTENTION_NOT_SCORE',
    'NET_DEBT_EBITDA_GT_4_IS_VETO',
    'ROIC_LEVEL_REQUIRES_DIRECTIONAL_CONTEXT',
    'CYCLICAL_PEAK_REQUIRES_NORMALIZED_EARNINGS',
  ] as const,
  implementation: 'src/atlas/algorithm/reverse-screener-discovery-omega.ts',
  tests: 'src/atlas/algorithm/reverse-screener-discovery-omega.test.ts',
  canonicalDocument: 'CURRENT_CANON/2026-09-09_REVERSE_SCREENER_DISCOVERY_OMEGA_V1_1.md',
  supersededDocument: 'CURRENT_CANON/2026-09-09_REVERSE_SCREENER_DISCOVERY_OMEGA_V1_0.md',
} as const;
