export const REVERSE_SCREENER_DISCOVERY_OMEGA_REGISTRY = {
  version: '2026-09-09-v1.0.0',
  status: 'ACTIVE_CANONICAL_RESEARCH_DISCOVERY',
  module: 'REVERSE_SCREENER_DISCOVERY_OMEGA_V1',
  insertion: 'R0_DISCOVERY_BEFORE_E1_FULL_EVIDENCE_AND_BEFORE_CAPITAL_SELECTION',
  directCapitalAuthority: false,
  scoreWeights: {
    fundamentalAcceleration: 0.25,
    earningsRevisions: 0.20,
    fcfQuality: 0.15,
    valuation: 0.15,
    priceMomentum: 0.15,
    catalyst: 0.10,
  } as const,
  gates: {
    marketCapUsdBnMin: 1,
    minimumAccelerationHits: 2,
    netDebtToEbitdaMax: 3,
    operatingMarginPctMin: 10,
    roicPctMin: 8,
    forwardPeMax: 30,
    evToEbitdaMax: 18,
    fcfYieldPctMin: 4,
    requiresPriceAboveMa200: true,
    requiresPositive3m: true,
    requiresPositive6m: true,
  } as const,
  cycleNormalization: {
    triggerEarningsAboveFiveYearNormPct: 50,
    appliesToCommodityOrCyclicalRegimes: true,
    scorePenalty: 10,
  } as const,
  invariants: [
    'DISCOVERY_SCORE_NEVER_BUY_ALONE',
    'DISCOVERY_SCORE_NEVER_PORTFOLIO_WEIGHT',
    'STRUCTURAL_AND_CYCLICAL_REGIMES_NOT_COMPARABLE_WITH_RAW_PE',
    'CYCLICAL_PEAK_REQUIRES_NORMALIZED_EARNINGS',
    'MOMENTUM_CANNOT_REPAIR_FAILED_QUALITY',
    'VALUATION_CANNOT_REPAIR_FAILED_ECONOMIC_PROOF',
  ] as const,
  implementation: 'src/atlas/algorithm/reverse-screener-discovery-omega.ts',
  tests: 'src/atlas/algorithm/reverse-screener-discovery-omega.test.ts',
  canonicalDocument: 'CURRENT_CANON/2026-09-09_REVERSE_SCREENER_DISCOVERY_OMEGA_V1_0.md',
} as const;
