export const ATLAS_CORE_UNIVERSE_VERSION = 'ATLAS_CORE_650_RAW_490_UNIQUE_487_ENTITY_2026-09-06' as const;
export const ATLAS_CORE_PLUS_VRT_UNIVERSE_VERSION = 'ATLAS_CORE_487_PLUS_VRT_ADMITTED_488_2026-09-06' as const;

const CORE_487 = `
AAPL MSFT NVDA GOOGL AVGO ADBE AMD AMAT ASML ARM APP TEAM ADSK CDNS CRWD DDOG FTNT INTC INTU KLAC
LRCX MRVL MCHP MU MPWR NXPI PANW QCOM ROP STX SNPS TER TXN WDC WDAY AMZN META NFLX BKNG DASH
EBAY MELI PYPL SHOP TTD TSLA ABNB CCEP COST KDP KHC MAR MDLZ MNST ORLY PEP ROST SBUX TTWO WBD
ALNY AMGN AZN AXON BIIB DXCM GILD IDXX ILMN INSM ISRG MRNA REGN VRTX CHTR CMCSA TMUS ADP BKR CTAS
CTSH CPRT CSX FANG FAST FER GEHC HON ODFL PCAR PAYX VRSK AEP CEG EXC XEL CSCO LIN CSGP PLTR
ORCL DELL ANET IBM CRM APH ADI VRSN AKAM GEN EPAM IT JBL PTC FFIV ZS HPQ NTAP SMCI TRMB
TEL KEYS CDW TYL GLW FI TDY ZBRA ENPH SWKS QRVO VZ DIS T EA OMC IPG LYV FOXA PARA
MTCH HD MCD LOW TJX NKE AZO HLT CMG GM F DHI LEN DRI YUM RCL CCL MGM WYNN EXPE
APTV TSCO ULTA GRMN NVR POOL DPZ BBY HAS WMT KO PG PM MO CL TGT SYY GIS KMB MKC
HSY ADM CAG SJM TSN CLX EL KVUE DG DLTR KR BRK.B JPM V MA BAC MS GS WFC AXP
C SCHW BLK SPGI CB PGR ICE CME MMC MCO AON PNC USB COF TFC AIG MET PRU TRV AJG
DFS FITB HBAN NTRS TROW CINF NDAQ ACGL STT BK MTB RF CFG KEY FIS GPN LLY JNJ ABBV MRK
UNH TMO ABT DHR PFE MDT SYK CI ELV ZTS BSX BDX HUM CVS CAH MCK ZBH A IQV RMD
EW HCA WAT HSIC MTD LH DGX STE COO CAT GE RTX GEV UNP LMT NOC GD BA DE ETN
UPS FDX NSC ITW EMR PH TT TDG CARR DOV EXPD CHRW LUV DAL UAL MMM SWK ROK AME HUBB
GWW XOM CVX COP EOG SLB MPC PSX VLO WMB OKE HAL HES OXY DVN KMI APA CTRA TRGP ECL
APD SHW FCX NUE DOW DD PPG VMC MLM STLD BALL AVY ALB MOS CF NEE SO DUK SRE D
PCG PEG ED WEC DTE ES NI AEE ETR CNP PLD AMT EQIX CCI PSA WELL DLR O SPG VTR
EXR SBAC AVB EQR HST IRM ENTG SNX DAY DXC VRNT NWSA BWA KMX LKQ NCLH PENN PVH RL TPR
VFC WHR CZR CPB CHD HRL LW TAP WBA AFL ALL ALLY AMP AIZ CBOE CMA EG FDS GL IVZ
JEF LNC L MKTX PFG RJF SYF WRB WTW ZION ALGN BIO TECH CRL XRAY INCY PODD MOH OGN RVTY
TFX UHS VTRIS WST AOS ALK ALLE AAL GNRC HII JBHT MAS PNR PWR RHI ROL SNA TXT WAB XYL
EQT MRO DINO FTI AMCR ATR CE CTVA EMN FMC IP PKG SEE SW AES LNT AWK ATO CMS FE
NRG PNW PPL ARE BXP CPT FRT DOC KIM MAA UDR VICI WPC BR BF.B CTLT ERIE EVRG CPAY HWM
J LULU OTIS VLTO ACN BAX BMY
`.trim().split(/\s+/).map(x => x.toUpperCase());

if (CORE_487.length !== 487 || new Set(CORE_487).size !== 487) {
  throw new Error('ATLAS_CORE_487_REGISTRY_CORRUPT');
}

export type StructuralUniverseAuthorityVersion =
  | typeof ATLAS_CORE_UNIVERSE_VERSION
  | typeof ATLAS_CORE_PLUS_VRT_UNIVERSE_VERSION;

export type StructuralUniverseAuthority = {
  version: StructuralUniverseAuthorityVersion;
  rawUniverseSource: string;
  expectedCanonicalEntityCount: number;
  allowedTickers: readonly string[];
  normalizedUniverseHash: string;
  admittedExternalTickers: readonly string[];
};

const CORE_AUTHORITY: StructuralUniverseAuthority = {
  version: ATLAS_CORE_UNIVERSE_VERSION,
  rawUniverseSource: 'data/t0-universe-user-seed-2026-09-05.txt',
  expectedCanonicalEntityCount: 487,
  allowedTickers: Object.freeze([...CORE_487]),
  normalizedUniverseHash: 'sha256:6bcdb5e0823934cd68f29c89dfb4f633a727c2b4029fad161975d9abf2fe5d1b',
  admittedExternalTickers: Object.freeze([]),
};

const CORE_PLUS_VRT_AUTHORITY: StructuralUniverseAuthority = {
  version: ATLAS_CORE_PLUS_VRT_UNIVERSE_VERSION,
  rawUniverseSource: 'data/t0-universe-user-seed-2026-09-05.txt + CURRENT_CANON/2026-09-06_VRT_ADMITTED_EXTERNAL_CHALLENGER.md',
  expectedCanonicalEntityCount: 488,
  allowedTickers: Object.freeze([...CORE_487, 'VRT']),
  normalizedUniverseHash: 'sha256:b8850213b29c8df867031cb62736a7decf004a5aa77d87111346f6d1ee60b2cc',
  admittedExternalTickers: Object.freeze(['VRT']),
};

export function resolveStructuralUniverseAuthority(version: StructuralUniverseAuthorityVersion): StructuralUniverseAuthority {
  if (version === ATLAS_CORE_UNIVERSE_VERSION) return CORE_AUTHORITY;
  if (version === ATLAS_CORE_PLUS_VRT_UNIVERSE_VERSION) return CORE_PLUS_VRT_AUTHORITY;
  throw new Error('UNKNOWN_STRUCTURAL_UNIVERSE_AUTHORITY');
}

export function isTickerAllowedByStructuralUniverse(version: StructuralUniverseAuthorityVersion, ticker: string): boolean {
  return resolveStructuralUniverseAuthority(version).allowedTickers.includes(ticker.trim().toUpperCase());
}
