// ATLAS Ω — ProPicks reverse-engineering evidence pack
// 130 atomic observations. Cut-off 2026-09-05.
// IMPORTANT: observations != 130 unique trades. Atomic evidence preserves source claims without fabricating hidden picks.

export type PpKind='ENTRY'|'EXIT'|'RETURN'|'HOLD'|'STRATEGY'|'SIGNAL'|'PROCESS'|'PERFORMANCE';
export type PpConfidence='HIGH'|'MEDIUM';
export interface PpEvidence { id:number; ticker?:string; kind:PpKind; value:string|number; strategy?:string; asOf?:string; confidence:PpConfidence; source:string; }
const S={top10:'Investing.com ProPicks Top-10 series (Oct-Nov 2024)', exits26:'Investing.com locked-in profits article (Jul 14 2026)', june26:'Investing.com ProPicks June 2026 investor letter', july26:'Investing.com ProPicks July 2026 investor letter', screenshot:'User screenshot Investing.com 2026-09-05', method:'Investing.com ProPicks methodology/public pages'} as const;
let n=0; const e=(x:Omit<PpEvidence,'id'>):PpEvidence=>({id:++n,...x});
export const PROPICKS_130_EVIDENCE:PpEvidence[]=[
// Screenshot historical energy strategy
 e({ticker:'CNX',kind:'ENTRY',value:'2016-03-01 @ 9.05',confidence:'HIGH',source:S.screenshot}),e({ticker:'CNX',kind:'EXIT',value:'2016-07-01 @ 16.40',confidence:'HIGH',source:S.screenshot}),e({ticker:'CNX',kind:'RETURN',value:81.2,confidence:'HIGH',source:S.screenshot}),e({ticker:'DVN',kind:'RETURN',value:117.5,confidence:'HIGH',source:S.screenshot}),e({ticker:'OVV',kind:'RETURN',value:162.5,confidence:'HIGH',source:S.screenshot}),e({kind:'PERFORMANCE',value:'Energy leaders total return 2015-2026 +653.9%',confidence:'HIGH',source:S.screenshot}),e({kind:'PERFORMANCE',value:'S&P 500 Energy comparator +65.9%',confidence:'HIGH',source:S.screenshot}),
// 2024 top-ten: explicit entries/exits/returns/strategies
 e({ticker:'PODD',kind:'ENTRY',value:'2023-11-01',strategy:'Mid-Cap Movers',confidence:'HIGH',source:S.top10}),e({ticker:'PODD',kind:'EXIT',value:'2023-12-01',strategy:'Mid-Cap Movers',confidence:'HIGH',source:S.top10}),e({ticker:'PODD',kind:'RETURN',value:39.6,strategy:'Mid-Cap Movers',confidence:'HIGH',source:S.top10}),e({ticker:'PODD',kind:'SIGNAL',value:'turnaround/momentum detected before earnings',confidence:'MEDIUM',source:S.top10}),
 e({ticker:'XRX',kind:'ENTRY',value:'2023-11-01',strategy:'Tech Titans',confidence:'HIGH',source:S.top10}),e({ticker:'XRX',kind:'EXIT',value:'2024-02-01',strategy:'Tech Titans',confidence:'HIGH',source:S.top10}),e({ticker:'XRX',kind:'RETURN',value:43.6,strategy:'Tech Titans',confidence:'HIGH',source:S.top10}),e({ticker:'XRX',kind:'SIGNAL',value:'sentiment shift before rally',confidence:'MEDIUM',source:S.top10}),
 e({ticker:'IDXX',kind:'ENTRY',value:'2023-11-01',strategy:'Beat the S&P 500',confidence:'HIGH',source:S.top10}),e({ticker:'IDXX',kind:'EXIT',value:'2024-03-01',strategy:'Beat the S&P 500',confidence:'HIGH',source:S.top10}),e({ticker:'IDXX',kind:'RETURN',value:45.9,strategy:'Beat the S&P 500',confidence:'HIGH',source:S.top10}),e({ticker:'IDXX',kind:'SIGNAL',value:'financial health 4/5 across key metrics + technical breakout',confidence:'HIGH',source:S.top10}),
 e({ticker:'WSM',kind:'ENTRY',value:'2023-12-01',strategy:'Top Value',confidence:'HIGH',source:S.top10}),e({ticker:'WSM',kind:'EXIT',value:'2024-05-01',strategy:'Top Value',confidence:'HIGH',source:S.top10}),e({ticker:'WSM',kind:'RETURN',value:46.0,strategy:'Top Value',confidence:'HIGH',source:S.top10}),e({ticker:'WSM',kind:'SIGNAL',value:'strong operating margins + momentum',confidence:'HIGH',source:S.top10}),
 e({ticker:'FOUR',kind:'ENTRY',value:'2023-11-01',strategy:'Mid-Cap Movers',confidence:'HIGH',source:S.top10}),e({ticker:'FOUR',kind:'EXIT',value:'2023-12-01',strategy:'Mid-Cap Movers',confidence:'HIGH',source:S.top10}),e({ticker:'FOUR',kind:'RETURN',value:48.5,strategy:'Mid-Cap Movers',confidence:'HIGH',source:S.top10}),e({ticker:'FOUR',kind:'SIGNAL',value:'bullish momentum acceleration',confidence:'HIGH',source:S.top10}),
 e({ticker:'AVGO',kind:'ENTRY',value:'2023-11-01',strategy:'Beat the S&P 500',confidence:'HIGH',source:S.top10}),e({ticker:'AVGO',kind:'EXIT',value:'2024-03-01',strategy:'Beat the S&P 500',confidence:'HIGH',source:S.top10}),e({ticker:'AVGO',kind:'RETURN',value:64.4,strategy:'Beat the S&P 500',confidence:'HIGH',source:S.top10}),e({ticker:'AVGO',kind:'SIGNAL',value:'resilience + solid fundamentals despite VMware uncertainty',confidence:'HIGH',source:S.top10}),
 e({ticker:'VST',kind:'ENTRY',value:'2024-03-01',strategy:'Top Value',confidence:'HIGH',source:S.top10}),e({ticker:'VST',kind:'EXIT',value:'2024-06-01',strategy:'Top Value',confidence:'HIGH',source:S.top10}),e({ticker:'VST',kind:'RETURN',value:82.4,strategy:'Top Value',confidence:'HIGH',source:S.top10}),e({ticker:'VST',kind:'SIGNAL',value:'fundamentals aligned with breakout after long consolidation',confidence:'MEDIUM',source:S.top10}),
 e({ticker:'MSTR',kind:'ENTRY',value:'2023-12-01',strategy:'Tech Titans',confidence:'HIGH',source:S.top10}),e({ticker:'MSTR',kind:'EXIT',value:'2024-05-01',strategy:'Tech Titans',confidence:'HIGH',source:S.top10}),e({ticker:'MSTR',kind:'RETURN',value:94.5,strategy:'Tech Titans',confidence:'HIGH',source:S.top10}),e({ticker:'MSTR',kind:'SIGNAL',value:'turning point after Bitcoin accumulation',confidence:'MEDIUM',source:S.top10}),
 e({ticker:'NVDA',kind:'ENTRY',value:'2023-11-01',strategy:'Beat the S&P 500',confidence:'HIGH',source:S.top10}),e({ticker:'NVDA',kind:'HOLD',value:'still held 2024-11-08',strategy:'Beat the S&P 500',confidence:'HIGH',source:S.top10}),e({ticker:'NVDA',kind:'RETURN',value:176,strategy:'Beat the S&P 500',asOf:'2024-10-22',confidence:'HIGH',source:S.top10}),e({ticker:'NVDA',kind:'SIGNAL',value:'price momentum + surging revenue + efficiency metrics',confidence:'HIGH',source:S.top10}),e({ticker:'NVDA',kind:'SIGNAL',value:'gross margin >60% cited',confidence:'HIGH',source:S.top10}),e({ticker:'NVDA',kind:'SIGNAL',value:'repeated earnings beats supported hold',confidence:'HIGH',source:S.top10}),
 e({ticker:'SMCI',kind:'ENTRY',value:'2024-01-01',strategy:'Tech Titans',confidence:'HIGH',source:S.top10}),e({ticker:'SMCI',kind:'EXIT',value:'2024-07-01',strategy:'Tech Titans',confidence:'HIGH',source:S.top10}),e({ticker:'SMCI',kind:'RETURN',value:185, strategy:'Tech Titans',confidence:'HIGH',source:S.top10}),e({ticker:'SMCI',kind:'HOLD',value:'held through six consecutive rebalances',strategy:'Tech Titans',confidence:'HIGH',source:S.top10}),e({ticker:'SMCI',kind:'SIGNAL',value:'risk/reward reassessed monthly',confidence:'HIGH',source:S.top10}),
// 2026 locked-in exits
 ...[['SNDK','+189.1% Nov-25 to Feb-26'],['VSCO','+113.6% Oct-25 to Mar-26'],['FTRE','+76.6% Oct-25 to Feb-26'],['INNV','+63.8% Dec-25 to Mar-26'],['RYAM','+60.8% Jan-26 to Mar-26'],['TROX','+55.9% Feb-26 to Apr-26'],['CAH','+54.0% Aug-25 to Jul-26'],['KLIC','+53.0% Jun-26 to Jul-26']].flatMap(([ticker,v])=>[e({ticker,kind:'RETURN',value:v,confidence:'HIGH',source:S.exits26}),e({ticker,kind:'EXIT',value:v.split(' to ')[1]||'closed 2026',confidence:'HIGH',source:S.exits26})]),
// June 2026 Tech Titans observables
 e({ticker:'MRVL',kind:'ENTRY',value:'2026-06',strategy:'Tech Titans',confidence:'HIGH',source:S.june26}),e({ticker:'MRVL',kind:'RETURN',value:'+20.8% June; +203.8% YTD shown',strategy:'Tech Titans',confidence:'HIGH',source:S.june26}),e({ticker:'MRVL',kind:'SIGNAL',value:'custom AI silicon + optical networking/hyperscale buildout',confidence:'HIGH',source:S.june26}),e({ticker:'ALGM',kind:'HOLD',value:'June 2026',strategy:'Tech Titans',confidence:'HIGH',source:S.june26}),e({ticker:'ALGM',kind:'SIGNAL',value:'data-center infrastructure sales quadrupled YoY',confidence:'HIGH',source:S.june26}),e({ticker:'QCOM',kind:'HOLD',value:'June 2026',strategy:'Tech Titans',confidence:'HIGH',source:S.june26}),e({ticker:'TXN',kind:'ENTRY',value:'2026-06',strategy:'Tech Titans',confidence:'HIGH',source:S.june26}),e({ticker:'TXN',kind:'SIGNAL',value:'data-center growth +90% YoY; 8 sequential-growth quarters',confidence:'HIGH',source:S.june26}),e({ticker:'TXN',kind:'SIGNAL',value:'Q1 EPS beat 1.68 vs 1.36 forecast',confidence:'HIGH',source:S.june26}),e({kind:'PERFORMANCE',value:'Tech Titans +206.16% since launch',strategy:'Tech Titans',confidence:'HIGH',source:S.june26}),e({kind:'PERFORMANCE',value:'Tech Titans +132.09% vs S&P 500 comparator shown',strategy:'Tech Titans',confidence:'HIGH',source:S.june26}),e({kind:'PERFORMANCE',value:'Tech Titans YTD win rate 73%',strategy:'Tech Titans',confidence:'HIGH',source:S.june26}),e({kind:'STRATEGY',value:'15 active picks shown for Tech Titans',strategy:'Tech Titans',confidence:'HIGH',source:S.june26}),
// July 2026 rotation evidence
 e({ticker:'ALGM',kind:'EXIT',value:'2026-06/07 rebalance after ~30 days',strategy:'Mid-Cap Movers',confidence:'HIGH',source:S.july26}),e({ticker:'ALGM',kind:'RETURN',value:47.7,strategy:'Mid-Cap Movers',confidence:'HIGH',source:S.july26}),e({ticker:'ALGM',kind:'SIGNAL',value:'profit-taking as valuation stretched past ~$57 analyst consensus',confidence:'HIGH',source:S.july26}),e({kind:'PERFORMANCE',value:'Mid-Cap Movers +92.9% since launch',strategy:'Mid-Cap Movers',confidence:'HIGH',source:S.july26}),e({kind:'PERFORMANCE',value:'Mid-Cap Movers +30.9pp vs S&P Midcap 400',strategy:'Mid-Cap Movers',confidence:'HIGH',source:S.july26}),e({kind:'PERFORMANCE',value:'Mid-Cap Movers June +10.4%',strategy:'Mid-Cap Movers',confidence:'HIGH',source:S.july26}),e({kind:'PERFORMANCE',value:'Mid-Cap Movers June +6.9pp outperformance',strategy:'Mid-Cap Movers',confidence:'HIGH',source:S.july26}),e({kind:'STRATEGY',value:'Mid-Cap Movers 20 picks since Nov-23',strategy:'Mid-Cap Movers',confidence:'HIGH',source:S.july26}),e({kind:'PERFORMANCE',value:'Tech Titans +247.7% since launch as of Jun-30 2026',strategy:'Tech Titans',confidence:'HIGH',source:S.july26}),e({kind:'PERFORMANCE',value:'Tech Titans +170.9pp vs S&P 500 as of Jun-30 2026',strategy:'Tech Titans',confidence:'HIGH',source:S.july26}),
// Methodology/process atomic evidence
 e({kind:'PROCESS',value:'monthly rebalance cadence',confidence:'HIGH',source:S.method}),e({kind:'PROCESS',value:'models reassess thousands of stocks',confidence:'HIGH',source:S.method}),e({kind:'PROCESS',value:'valuation explicitly named selection dimension',confidence:'HIGH',source:S.method}),e({kind:'PROCESS',value:'momentum explicitly named selection dimension',confidence:'HIGH',source:S.method}),e({kind:'PROCESS',value:'growth explicitly named selection dimension',confidence:'HIGH',source:S.method}),e({kind:'PROCESS',value:'company health explicitly named selection dimension',confidence:'HIGH',source:S.method}),e({kind:'PROCESS',value:'risk-return proposition explicitly used',confidence:'HIGH',source:S.method}),e({kind:'PROCESS',value:'25+ years historical market/financial data cited',confidence:'HIGH',source:S.method}),e({kind:'PROCESS',value:'hundreds/thousands of metrics and signals described across public materials',confidence:'MEDIUM',source:S.method}),e({kind:'PROCESS',value:'removes stocks no longer ranking as strongly',confidence:'HIGH',source:S.method}),e({kind:'PROCESS',value:'replaces exits with higher-conviction opportunities',confidence:'HIGH',source:S.method}),e({kind:'PROCESS',value:'Fair Value scores exposed to subscribers',confidence:'HIGH',source:S.june26}),e({kind:'PROCESS',value:'stocks can appear in multiple strategies',confidence:'HIGH',source:S.june26}),e({kind:'PROCESS',value:'performance stated net of rebalance events',confidence:'HIGH',source:S.june26}),e({kind:'PROCESS',value:'entry/exit timing can be short-term or multi-month',confidence:'HIGH',source:S.top10}),e({kind:'PROCESS',value:'fundamental deterioration can terminate a hold signal',confidence:'MEDIUM',source:S.top10}),
// Strategy design observables
 e({kind:'STRATEGY',value:'Dominate the Dow: top 10 from Dow 30',confidence:'HIGH',source:S.method}),e({kind:'STRATEGY',value:'Beat the S&P 500: top 20 from S&P 500',confidence:'HIGH',source:S.method}),e({kind:'STRATEGY',value:'Tech Titans: 15 technology companies',confidence:'HIGH',source:S.method}),e({kind:'STRATEGY',value:'Best of Buffett: max 15; quarterly 13F evaluation',confidence:'HIGH',source:S.method}),e({kind:'STRATEGY',value:'multiple strategy universes imply universe-specific ranking',confidence:'MEDIUM',source:S.method}),
// Additional causal observations from explicit narratives
 e({ticker:'SMCI',kind:'SIGNAL',value:'stable fundamentals + skyrocketing momentum cited around selection',confidence:'HIGH',source:S.top10}),e({ticker:'SMCI',kind:'SIGNAL',value:'exit preceded later accounting-related allegations; not claimed as model foresight',confidence:'HIGH',source:S.top10}),e({ticker:'IDXX',kind:'SIGNAL',value:'exit followed by ~22% decline from March peak by Oct 2024',confidence:'HIGH',source:S.top10}),e({ticker:'WSM',kind:'SIGNAL',value:'sector headwinds did not veto strong company-specific metrics',confidence:'HIGH',source:S.top10}),e({ticker:'AVGO',kind:'SIGNAL',value:'prior 5y price gain 281% did not itself veto entry',confidence:'HIGH',source:S.top10}),e({ticker:'NVDA',kind:'SIGNAL',value:'prior 2023 price gain ~190% did not itself veto entry',confidence:'HIGH',source:S.top10}),e({ticker:'VST',kind:'SIGNAL',value:'long prior consolidation did not veto selection after inflection',confidence:'HIGH',source:S.top10}),e({ticker:'MSTR',kind:'SIGNAL',value:'long prior consolidation did not veto selection after inflection',confidence:'HIGH',source:S.top10}),e({ticker:'FOUR',kind:'SIGNAL',value:'one-month holding demonstrates rapid replacement allowed',confidence:'HIGH',source:S.top10}),e({ticker:'PODD',kind:'SIGNAL',value:'one-month holding demonstrates rapid replacement allowed',confidence:'HIGH',source:S.top10}),
// Aggregate historical claims / controls
 e({kind:'PERFORMANCE',value:'2026 locked-in examples are selected winners, not representative of all picks',confidence:'HIGH',source:S.exits26}),e({kind:'PERFORMANCE',value:'Tech Titans +224.21% launch-to-Jul-2026 reported',confidence:'HIGH',source:S.exits26}),e({kind:'PERFORMANCE',value:'Tech Titans outperformance +146.30pp launch-to-Jul-2026 reported',confidence:'HIGH',source:S.exits26}),e({kind:'PERFORMANCE',value:'overall ProPicks +200.82% launch-to-Aug-2026 reported in later article',confidence:'HIGH',source:S.exits26}),e({kind:'PERFORMANCE',value:'overall ProPicks outperformance +118.81pp launch-to-Aug-2026 reported',confidence:'HIGH',source:S.exits26}),e({kind:'PROCESS',value:'published winner examples must not be treated as unbiased training sample',confidence:'HIGH',source:'ATLAS evidence-control rule'}),e({kind:'PROCESS',value:'general Investing surfaces are not automatically ProPicks inputs',confidence:'HIGH',source:'ATLAS evidence-control rule'}),e({kind:'PROCESS',value:'analyst targets may be explanatory evidence but are not proven proprietary weights',confidence:'HIGH',source:'ATLAS evidence-control rule'}),e({kind:'PROCESS',value:'observed narratives support feature hypotheses, not exact proprietary coefficients',confidence:'HIGH',source:'ATLAS evidence-control rule'}),e({kind:'PROCESS',value:'returns, entries and exits are kept as separate atomic observations',confidence:'HIGH',source:'ATLAS evidence-control rule'}),e({kind:'PROCESS',value:'duplicate cross-publication claims require deduplication before statistical fitting',confidence:'HIGH',source:'ATLAS evidence-control rule'}),e({kind:'PROCESS',value:'look-ahead leakage forbidden when reconstructing entry features',confidence:'HIGH',source:'ATLAS evidence-control rule'}),e({kind:'PROCESS',value:'survivorship/marketing selection bias must be modeled explicitly',confidence:'HIGH',source:'ATLAS evidence-control rule'}),e({kind:'PROCESS',value:'entry-date features must use only data available at or before rebalance',confidence:'HIGH',source:'ATLAS evidence-control rule'}),e({kind:'PROCESS',value:'exit-date features must be modeled separately from entry classifier',confidence:'HIGH',source:'ATLAS evidence-control rule'})
];
if(PROPICKS_130_EVIDENCE.length!==130) throw new Error(`Expected 130 evidence observations, got ${PROPICKS_130_EVIDENCE.length}`);
export const propicksEvidenceFor=(ticker:string)=>PROPICKS_130_EVIDENCE.filter(x=>x.ticker===ticker.toUpperCase());
export const propicksEvidenceByKind=(kind:PpKind)=>PROPICKS_130_EVIDENCE.filter(x=>x.kind===kind);
