export const GRAN_ROTATION_2026_AUDIT = {
  id: 'AUDIT_GRAN_ROTATION_2026_08_09',
  asOf: '2026-08-09',
  verdict: 'REJECT_AS_DATASET_KEEP_AS_HYPOTHESIS',
  canonicalImpact: 'WATCH_ONLY',
  validatedObservations: [
    { asset: 'US_TECH_ETFS', window: 'H1_2026', netFlowUsdB: 44.760, source: 'STATE_STREET' },
    { asset: 'US_HEALTH_ETFS', window: 'H1_2026', netFlowUsdB: 1.018, source: 'STATE_STREET' },
    { asset: 'US_ENERGY_ETFS', window: 'H1_2026', netFlowUsdB: 9.421, source: 'STATE_STREET' },
    { asset: 'US_GROWTH_FUNDS', window: 'WEEK_ENDING_2026_08_05', netFlowUsdB: -5.500, source: 'LSEG_LIPPER' },
    { asset: 'US_VALUE_FUNDS', window: 'WEEK_ENDING_2026_08_05', netFlowUsdB: 1.990, source: 'LSEG_LIPPER' },
    { asset: 'US_HEALTH_FUNDS', window: 'WEEK_ENDING_2026_08_05', netFlowUsdB: 0.866, source: 'LSEG_LIPPER' },
    { asset: 'US_INDUSTRIAL_FUNDS', window: 'WEEK_ENDING_2026_08_05', netFlowUsdB: 0.875, source: 'LSEG_LIPPER' },
  ],
  rejectedClaims: [
    { claim: 'TOTAL_ROTATION_USD_2_5T', reason: 'NON_REPRODUCIBLE_MIXED_MAGNITUDES' },
    { claim: 'TECH_ETF_OUTFLOW_USD_450B', reason: 'CONTRADICTED_BY_STATE_STREET' },
    { claim: 'HEALTH_INFLOW_USD_65_TO_80B', reason: 'MAGNITUDE_NOT_SUPPORTED' },
    { claim: 'ENERGY_INFLOW_USD_180B', reason: 'MAGNITUDE_NOT_SUPPORTED' },
    { claim: 'GOLD_ETF_INFLOW_USD_120B', reason: 'MAGNITUDE_NOT_SUPPORTED' },
    { claim: 'DEFENSE_INFLOW_USD_150B', reason: 'BUDGET_AND_AUM_ARE_NOT_FLOWS' },
  ],
  atlasRouting: {
    health: 'R3_CANDIDATE_MONITOR',
    industrials: 'R3_CANDIDATE_MONITOR',
    technology: 'NO_STRUCTURAL_EXIT_CONFIRMED',
    bonds: 'CROSS_ASSET_REGIME_CONFIRMED',
    energy: 'LATE_OR_CROWDED_MONITOR',
    gold: 'TACTICAL_MODULE_SEPARATE',
    defense: 'CATALYST_VALID_FLOW_UNCONFIRMED',
  },
  sources: [
    'https://www.ssga.com/us/en/intermediary/insights/etf-inflows-set-records-in-first-half',
    'https://www.reuters.com/business/retail-consumer/us-equity-funds-see-outflows-investors-take-profits-ahead-jobs-data-2026-08-07/',
    'https://www.ici.org/research/stats/combined_flows',
    'https://www.gold.org/goldhub/data/global-gold-backed-etf-holdings-and-flows',
    'https://www.eia.gov/outlooks/steo/report/global_oil.php',
    'https://www.federalreserve.gov/newsevents/pressreleases/monetary20260729a.htm',
  ],
} as const;
