from __future__ import annotations

from typing import Any


ATLAS_TOP_80: list[dict[str, Any]] = [
    {"ticker": "MSFT", "name": "Microsoft", "sector": "Technology", "subsector": "Software / Cloud / AI", "country": "USA", "atlasRole": "Core compounder"},
    {"ticker": "GOOG", "name": "Alphabet", "sector": "Communication Services", "subsector": "Search / Cloud / AI", "country": "USA", "atlasRole": "Core compounder"},
    {"ticker": "NVDA", "name": "NVIDIA", "sector": "Technology", "subsector": "Semiconductors / AI", "country": "USA", "atlasRole": "Core compounder; valuation gated"},
    {"ticker": "TSM", "name": "Taiwan Semiconductor", "sector": "Technology", "subsector": "Foundry semiconductors", "country": "Taiwan", "atlasRole": "Core compounder"},
    {"ticker": "ASML", "name": "ASML", "sector": "Technology", "subsector": "Semiconductor equipment", "country": "Netherlands", "atlasRole": "Core compounder"},
    {"ticker": "AVGO", "name": "Broadcom", "sector": "Technology", "subsector": "Semiconductors / infrastructure", "country": "USA", "atlasRole": "Core compounder"},
    {"ticker": "AMZN", "name": "Amazon", "sector": "Consumer Discretionary", "subsector": "Cloud / e-commerce", "country": "USA", "atlasRole": "Core compounder"},
    {"ticker": "META", "name": "Meta Platforms", "sector": "Communication Services", "subsector": "Ads / AI / platforms", "country": "USA", "atlasRole": "Core compounder"},
    {"ticker": "AAPL", "name": "Apple", "sector": "Technology", "subsector": "Hardware / ecosystem", "country": "USA", "atlasRole": "Quality; growth watch"},
    {"ticker": "V", "name": "Visa", "sector": "Financials", "subsector": "Payments", "country": "USA", "atlasRole": "Core compounder"},
    {"ticker": "MA", "name": "Mastercard", "sector": "Financials", "subsector": "Payments", "country": "USA", "atlasRole": "Core compounder"},
    {"ticker": "COST", "name": "Costco", "sector": "Consumer Staples", "subsector": "Defensive retail", "country": "USA", "atlasRole": "Quality; valuation gated"},
    {"ticker": "LLY", "name": "Eli Lilly", "sector": "Health Care", "subsector": "Pharma / obesity", "country": "USA", "atlasRole": "Health compounder; valuation gated"},
    {"ticker": "NVO", "name": "Novo Nordisk", "sector": "Health Care", "subsector": "Pharma / obesity", "country": "Denmark", "atlasRole": "Health compounder"},
    {"ticker": "ISRG", "name": "Intuitive Surgical", "sector": "Health Care", "subsector": "Medtech", "country": "USA", "atlasRole": "Core compounder"},
    {"ticker": "IDXX", "name": "IDEXX", "sector": "Health Care", "subsector": "Animal diagnostics", "country": "USA", "atlasRole": "Quality compounder"},
    {"ticker": "DHR", "name": "Danaher", "sector": "Health Care", "subsector": "Life sciences", "country": "USA", "atlasRole": "Recovery compounder"},
    {"ticker": "TMO", "name": "Thermo Fisher", "sector": "Health Care", "subsector": "Life sciences", "country": "USA", "atlasRole": "Core compounder"},
    {"ticker": "ABT", "name": "Abbott", "sector": "Health Care", "subsector": "Medtech / diagnostics", "country": "USA", "atlasRole": "Defensive quality"},
    {"ticker": "BSX", "name": "Boston Scientific", "sector": "Health Care", "subsector": "Medtech", "country": "USA", "atlasRole": "Quality growth"},
    {"ticker": "SYK", "name": "Stryker", "sector": "Health Care", "subsector": "Medtech", "country": "USA", "atlasRole": "Core compounder"},
    {"ticker": "ZTS", "name": "Zoetis", "sector": "Health Care", "subsector": "Animal health", "country": "USA", "atlasRole": "Contrarian quality"},
    {"ticker": "UNH", "name": "UnitedHealth", "sector": "Health Care", "subsector": "Managed care", "country": "USA", "atlasRole": "Quality; regulatory risk"},
    {"ticker": "MCK", "name": "McKesson", "sector": "Health Care", "subsector": "Health distribution", "country": "USA", "atlasRole": "Defensive FCF compounder"},
    {"ticker": "SPGI", "name": "S&P Global", "sector": "Financials", "subsector": "Financial data", "country": "USA", "atlasRole": "Core compounder"},
    {"ticker": "MCO", "name": "Moody's", "sector": "Financials", "subsector": "Ratings / data", "country": "USA", "atlasRole": "Core compounder"},
    {"ticker": "ICE", "name": "Intercontinental Exchange", "sector": "Financials", "subsector": "Exchanges / data", "country": "USA", "atlasRole": "Core compounder"},
    {"ticker": "CME", "name": "CME Group", "sector": "Financials", "subsector": "Exchanges", "country": "USA", "atlasRole": "Defensive quality"},
    {"ticker": "MSCI", "name": "MSCI", "sector": "Financials", "subsector": "Indexes / data", "country": "USA", "atlasRole": "Core compounder; valuation watch"},
    {"ticker": "BRK.B", "name": "Berkshire Hathaway", "sector": "Financials", "subsector": "Holding / insurance", "country": "USA", "atlasRole": "Defensive quality"},
    {"ticker": "JPM", "name": "JPMorgan Chase", "sector": "Financials", "subsector": "Banking", "country": "USA", "atlasRole": "Global bank quality"},
    {"ticker": "BLK", "name": "BlackRock", "sector": "Financials", "subsector": "Asset management", "country": "USA", "atlasRole": "Quality; market sensitive"},
    {"ticker": "BX", "name": "Blackstone", "sector": "Financials", "subsector": "Alternatives", "country": "USA", "atlasRole": "Quality; cyclical"},
    {"ticker": "SCHW", "name": "Charles Schwab", "sector": "Financials", "subsector": "Brokerage / wealth", "country": "USA", "atlasRole": "Quality; rates watch"},
    {"ticker": "ADP", "name": "Automatic Data Processing", "sector": "Industrials", "subsector": "Payroll software", "country": "USA", "atlasRole": "Defensive compounder"},
    {"ticker": "INTU", "name": "Intuit", "sector": "Technology", "subsector": "Financial software", "country": "USA", "atlasRole": "Core compounder"},
    {"ticker": "NOW", "name": "ServiceNow", "sector": "Technology", "subsector": "Enterprise software", "country": "USA", "atlasRole": "Growth compounder"},
    {"ticker": "CRM", "name": "Salesforce", "sector": "Technology", "subsector": "Enterprise software", "country": "USA", "atlasRole": "Mature quality"},
    {"ticker": "ADBE", "name": "Adobe", "sector": "Technology", "subsector": "Creative software", "country": "USA", "atlasRole": "Contrarian quality"},
    {"ticker": "PLTR", "name": "Palantir", "sector": "Technology", "subsector": "AI software", "country": "USA", "atlasRole": "High growth; valuation gated"},
    {"ticker": "SNPS", "name": "Synopsys", "sector": "Technology", "subsector": "EDA software", "country": "USA", "atlasRole": "Semiconductor core"},
    {"ticker": "CDNS", "name": "Cadence", "sector": "Technology", "subsector": "EDA software", "country": "USA", "atlasRole": "Semiconductor core"},
    {"ticker": "ANET", "name": "Arista Networks", "sector": "Technology", "subsector": "AI/data-center networking", "country": "USA", "atlasRole": "Infrastructure compounder"},
    {"ticker": "PANW", "name": "Palo Alto Networks", "sector": "Technology", "subsector": "Cybersecurity", "country": "USA", "atlasRole": "Digital protectors"},
    {"ticker": "CRWD", "name": "CrowdStrike", "sector": "Technology", "subsector": "Cybersecurity", "country": "USA", "atlasRole": "Digital protectors"},
    {"ticker": "FTNT", "name": "Fortinet", "sector": "Technology", "subsector": "Cybersecurity", "country": "USA", "atlasRole": "Quality / margin"},
    {"ticker": "NET", "name": "Cloudflare", "sector": "Technology", "subsector": "Edge / security", "country": "USA", "atlasRole": "Growth; profitability watch"},
    {"ticker": "ORCL", "name": "Oracle", "sector": "Technology", "subsector": "Cloud / database", "country": "USA", "atlasRole": "AI infrastructure; leverage watch"},
    {"ticker": "SAP", "name": "SAP", "sector": "Technology", "subsector": "Enterprise software", "country": "Germany", "atlasRole": "Europe core"},
    {"ticker": "CSU.TO", "name": "Constellation Software", "sector": "Technology", "subsector": "Vertical software", "country": "Canada", "atlasRole": "Quality compounder"},
    {"ticker": "ROP", "name": "Roper Technologies", "sector": "Industrials", "subsector": "Vertical software / industrial tech", "country": "USA", "atlasRole": "Core compounder"},
    {"ticker": "HEI", "name": "HEICO", "sector": "Industrials", "subsector": "Aerospace components", "country": "USA", "atlasRole": "Quality compounder"},
    {"ticker": "TDG", "name": "TransDigm", "sector": "Industrials", "subsector": "Aerospace components", "country": "USA", "atlasRole": "Core; leverage watch"},
    {"ticker": "SAF.PA", "name": "Safran", "sector": "Industrials", "subsector": "Aerospace / engines", "country": "France", "atlasRole": "Europe core"},
    {"ticker": "GE", "name": "GE Aerospace", "sector": "Industrials", "subsector": "Aerospace engines", "country": "USA", "atlasRole": "Core compounder"},
    {"ticker": "RTX", "name": "RTX", "sector": "Industrials", "subsector": "Aerospace / defense", "country": "USA", "atlasRole": "Defense quality"},
    {"ticker": "LMT", "name": "Lockheed Martin", "sector": "Industrials", "subsector": "Defense", "country": "USA", "atlasRole": "Defensive"},
    {"ticker": "NOC", "name": "Northrop Grumman", "sector": "Industrials", "subsector": "Defense", "country": "USA", "atlasRole": "Defensive / geopolitics"},
    {"ticker": "ETN", "name": "Eaton", "sector": "Industrials", "subsector": "Electrification", "country": "Ireland / USA", "atlasRole": "Infrastructure compounder"},
    {"ticker": "VRT", "name": "Vertiv", "sector": "Industrials", "subsector": "Data centers / cooling", "country": "USA", "atlasRole": "AI infrastructure; valuation watch"},
    {"ticker": "TT", "name": "Trane Technologies", "sector": "Industrials", "subsector": "HVAC / efficiency", "country": "Ireland / USA", "atlasRole": "Industrial compounder"},
    {"ticker": "PH", "name": "Parker-Hannifin", "sector": "Industrials", "subsector": "Industrial motion", "country": "USA", "atlasRole": "Industrial compounder"},
    {"ticker": "ITW", "name": "Illinois Tool Works", "sector": "Industrials", "subsector": "Industrial", "country": "USA", "atlasRole": "Quality compounder"},
    {"ticker": "FAST", "name": "Fastenal", "sector": "Industrials", "subsector": "Industrial distribution", "country": "USA", "atlasRole": "Core compounder"},
    {"ticker": "CTAS", "name": "Cintas", "sector": "Industrials", "subsector": "B2B services", "country": "USA", "atlasRole": "Core compounder"},
    {"ticker": "CPRT", "name": "Copart", "sector": "Industrials", "subsector": "Auto auctions", "country": "USA", "atlasRole": "Asset-light compounder"},
    {"ticker": "BKNG", "name": "Booking Holdings", "sector": "Consumer Discretionary", "subsector": "Travel platform", "country": "USA", "atlasRole": "Core compounder"},
    {"ticker": "MELI", "name": "MercadoLibre", "sector": "Consumer Discretionary", "subsector": "E-commerce / fintech", "country": "Argentina / LatAm", "atlasRole": "Emerging-market compounder"},
    {"ticker": "SE", "name": "Sea", "sector": "Consumer Discretionary", "subsector": "E-commerce / gaming / fintech", "country": "Singapore", "atlasRole": "Higher-risk growth"},
    {"ticker": "TCEHY", "name": "Tencent", "sector": "Communication Services", "subsector": "Internet / gaming / cloud", "country": "China", "atlasRole": "China quality; policy risk"},
    {"ticker": "BABA", "name": "Alibaba", "sector": "Consumer Discretionary", "subsector": "E-commerce / cloud", "country": "China", "atlasRole": "Contrarian quality"},
    {"ticker": "JD", "name": "JD.com", "sector": "Consumer Discretionary", "subsector": "E-commerce / logistics", "country": "China", "atlasRole": "Historical dislocation"},
    {"ticker": "HDB", "name": "HDFC Bank", "sector": "Financials", "subsector": "Banking", "country": "India", "atlasRole": "India core"},
    {"ticker": "TCS.NS", "name": "Tata Consultancy Services", "sector": "Technology", "subsector": "IT services", "country": "India", "atlasRole": "Defensive quality"},
    {"ticker": "RELIANCE.NS", "name": "Reliance Industries", "sector": "Energy", "subsector": "Energy / retail / telecom", "country": "India", "atlasRole": "Strategic conglomerate"},
    {"ticker": "LIN", "name": "Linde", "sector": "Materials", "subsector": "Industrial gases", "country": "UK / USA", "atlasRole": "Defensive compounder"},
    {"ticker": "SHW", "name": "Sherwin-Williams", "sector": "Materials", "subsector": "Coatings", "country": "USA", "atlasRole": "Pricing power"},
    {"ticker": "ECL", "name": "Ecolab", "sector": "Materials", "subsector": "Water / hygiene", "country": "USA", "atlasRole": "Defensive quality"},
    {"ticker": "XOM", "name": "Exxon Mobil", "sector": "Energy", "subsector": "Integrated energy", "country": "USA", "atlasRole": "Energy Rotation audit"},
    {"ticker": "SHEL", "name": "Shell", "sector": "Energy", "subsector": "Integrated energy / LNG", "country": "UK", "atlasRole": "Energy Rotation audit"},
]
